// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

export function renderAdmission(){
  if(!admap){admap=L.map('admap').setView([school?school.latitude:27.578,school?school.longitude:75.137],12);
    addBaseLayer(admap);
    if(school)L.marker([school.latitude,school.longitude],{icon:L.divIcon({className:'',html:'<div style="font-size:20px">🏫</div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(admap);
    admap.on('click',e=>{setAdPin(e.latlng.lat,e.latlng.lng);suggest(e.latlng.lat,e.latlng.lng);});}
  setTimeout(()=>admap.invalidateSize(),60);
  $('adGo').onclick=()=>{const p=($('adCoord').value||'').split(',').map(Number);
    if(p.length===2&&!isNaN(p[0])){setAdPin(p[0],p[1]);admap.setView([p[0],p[1]],15);suggest(p[0],p[1]);}
    else toast('Enter as: lat, lon','bad');};
}

export function setAdPin(lat,lon){if(!adpin){adpin=L.marker([lat,lon],{draggable:true}).addTo(admap);
    adpin.on('dragend',()=>{const p=adpin.getLatLng();$('adCoord').value=`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}`;suggest(p.lat,p.lng);});}
  else adpin.setLatLng([lat,lon]);$('adCoord').value=`${(+lat).toFixed(6)}, ${(+lon).toFixed(6)}`;}

export async function suggest(lat,lon){
  $('adOut').innerHTML='<div class="hint">Working out the detour, fuel and time for each bus…</div>';
  const {data,error}=await db.rpc('assign_impact',{p_lat:lat,p_lon:lon,p_n:4});
  if(error){$('adOut').innerHTML='<div class="note">'+esc(error.message)+'</div>';return;}
  if(!data||!data.length){$('adOut').innerHTML='<div class="note">No routes found.</div>';return;}
  const cell=(l,v)=>`<div class="coord" style="padding:6px 8px"><div class="k">${l}</div><div class="v">${v}</div></div>`;
  $('adOut').innerHTML=`<div class="note" style="margin-bottom:8px">The bus detours to collect the student. Lower detour = less added fuel and less delay for everyone already on board. Student’s own distance/time to school is road-estimated.</div>`+
    data.map(r=>`
    <div style="border:1px solid ${r.recommended?'var(--signal)':'var(--edge)'};border-radius:8px;padding:12px;margin-bottom:10px;background:${r.recommended?'#fff8e8':'#fff'}">
      <div style="display:flex;align-items:baseline;gap:8px"><b style="font-size:16px">Bus ${r.bus_id}</b>
        ${r.recommended?'<span class="flag" style="background:var(--signal);color:#000;border:none">Least detour, has room</span>':''}
        ${!r.has_room?'<span class="flag" style="color:var(--stop)">full</span>':''}</div>
      <div class="grid" style="margin:8px 0">
        ${cell('Route detour',r.detour_km+' km')}
        ${cell('Added fuel / yr','₹'+Number(r.extra_annual_fuel).toLocaleString('en-IN'))}
        ${cell('Adds to trip','+'+r.detour_min+' min')}
        ${cell('Student to school',r.student_km_school+' km · ~'+r.student_min_school+' min')}
        ${cell('Seats',r.seats_left+' of '+r.effective_capacity+' free')}
      </div>
      <button class="b-primary assignBtn" data-bus="${r.bus_id}" data-lat="${lat}" data-lon="${lon}" ${!r.has_room?'disabled':''} style="padding:6px 12px;font-size:12px">Assign to Bus ${r.bus_id}</button>
    </div>`).join('');
  [...document.querySelectorAll('.assignBtn')].forEach(b=>b.onclick=()=>assignAdmission(b.dataset));
}

export async function assignAdmission(d){
  const sr=prompt('Enter the new student’s SR number to assign to Bus '+d.bus+':');if(!sr)return;
  const name=prompt('Student name (optional):')||('SR '+sr);
  const {error}=await db.from('students').update({bus_no:parseInt(d.bus,10),latitude:+(+d.lat).toFixed(6),longitude:+(+d.lon).toFixed(6)}).eq('sr_no',sr.trim());
  if(error){toast(error.message.includes('0 rows')||error.details? 'No student with SR '+sr+' — add them first, then assign':error.message,'bad');return;}
  toast(`Assigned ${name} to Bus ${d.bus}`,'good');loadDashboard();
}

Object.assign(globalThis, { renderAdmission, setAdPin, suggest, assignAdmission });
