// Generated by tools/autorefactor.py. Original saved in backups/.
import { start } from "./bootstrap.js";
import { navigate } from "./router.js";
import { db } from "./supabase.js";
import "./utils.js";
import "./maps.js";
import "./dashboard.js";
import "./students.js";
import "./pickup.js";
import "./temporary.js";
import "./routes.js";
import "./optimization.js";
import "./planner.js";
import "./reports.js";
import "./buspage.js";
import "./admission.js";
import "./ask.js";
import "./bulk.js";

globalThis.SUPABASE_URL = 'https://ftlaicvkwmxkehlefeap.supabase.co';
globalThis.SUPABASE_KEY = 'sb_publishable_N4uceGsyAcLOUl_nDgzRbw_HhJCbcOZ';
// PostgREST returns at most 1000 rows per request; page through so we get every student
                                       
                                 
              
                                                                                 
                                          
                             
                                  
            
   
             
 

// ===================================================================
//  PASTE YOUR GOOGLE MAPS API KEY BETWEEN THE QUOTES BELOW.
//  Leave it empty ('') to keep the free OpenStreetMap basemap.
//  NOTE: Google Maps often will NOT load from a file opened directly
//  (a file:/// address). If the Google layer doesn't appear, the map
//  still works on OpenStreetMap. See the notes for how to serve the
//  file so Google works.
const GOOGLE_MAPS_API_KEY = '';
// ===================================================================
globalThis.googleReady = false;

// ===================================================================
globalThis.googleFailed = false;

// ===================================================================
globalThis.allMaps = [];

// ===================================================================
globalThis.googleLayers = [];
// Google calls this automatically when the key is invalid / unauthorised / billing off.
window.gm_authFailure=function(){googleFailed=true;
  googleLayers.forEach(g=>{try{g.remove();}catch(e){}});googleLayers=[];
  console.warn('Google Maps could not authorise this key here — using OpenStreetMap.');};
                      
                                  
                                           
                                                                             
               
                                                                  
                                     
                               
 
loadGoogle();
                         
                                                                                                 
                                                            
                                                                                                               
 
// Every map gets OpenStreetMap first (so it is NEVER blank); Google layers on top only if it works.
                         
                                                                                                                             
                                   
 
const $=id=>document.getElementById(id);
globalThis.esc = s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
globalThis.rs = n=>'₹'+Number(n||0).toLocaleString('en-IN');
                                                                                                                        
                                                                                                                                                                 

globalThis.map = undefined;

                                                                                                                        
                                                                                                                                                                 

globalThis.pin = undefined;

                                                                                                                        
                                                                                                                                                                 

globalThis.buses = [];

                                                                                                                        
                                                                                                                                                                 

globalThis.school = null;

                                                                                                                        
                                                                                                                                                                 

globalThis.current = null;

                                                                                                                        
                                                                                                                                                                 

globalThis.colorOf = {};

                                                                                                                        
                                                                                                                                                                 

globalThis.routeMap = undefined;

                                                                                                                        
                                                                                                                                                                 

globalThis.mapLayers = {};

                                                                                                                        
                                                                                                                                                                 

globalThis.mapReady = false;

                                                                                                                        
                                                                                                                                                                 

globalThis.checkedBuses = new Set();

/* auth */
$('loginBtn').onclick=async()=>{const b=$('loginBtn');b.disabled=true;$('gateMsg').textContent='Checking…';
  const {error}=await db.auth.signInWithPassword({email:$('em').value.trim(),password:$('pw').value});b.disabled=false;
  if(error){$('gateMsg').innerHTML='<span style="color:#b42318">'+esc(error.message)+'</span>';return;}start();};
$('pw').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click();});
$('outBtn').onclick=async()=>{await db.auth.signOut();location.reload();};
// Session resume is handled once by the DOMContentLoaded listener at the end of this file.


document.querySelectorAll('nav button').forEach(btn=>btn.onclick=()=>{
  document.querySelectorAll('nav button').forEach(b=>b.classList.remove('on'));btn.classList.add('on');
  document.querySelectorAll('.view').forEach(v=>v.classList.remove('on'));
  $('v-'+btn.dataset.view).classList.add('on');
  const v=btn.dataset.view;
  if(v==='dash')loadDashboard();
  if(v==='map')openRouteMap();
  if(v==='students')setTimeout(()=>map&&map.invalidateSize(),60);
  if(v==='opt')renderOptimization();
  if(v==='planner')renderPlanner();
  if(v==='bulk')renderBulk();
  if(v==='reports')renderReports();
  if(v==='ask')renderAsk();
  if(v==='admission')renderAdmission();
  if(v==='buspage')renderBusPage();
});

/* ============ DASHBOARD ============ */

/* ============ STUDENTS ============ */
                       
                                                                                                                 
                    
                                                                                                                                                                                                        
                                                                          
 
                              
                                                                                                                                          
                                
                                                                                           
                                                    
 
globalThis.stimer = undefined;$('q').addEventListener('input',e=>{clearTimeout(stimer);stimer=setTimeout(()=>searchStudents(e.target.value),220);});
                                                     
                                                                                                       
                                                                                                                                                                                                    
                                                                                            
                                            
 
                                      
                                                                                    
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                     
 
                               
                                                                                         
                                               
                                        
                                                                                                                               
                                                                                                                      
                                                         
                                                     
                                                                                                       
                                                                          
                                                                      
                                                                                         
                                                                                                                                                                                   
                                                                                                
                                                                                                        
                                                                                                                            
                                                                                                
                                                                                                                                          
                                                                                                            
                                                                                                                                                                                              
                                                                                                                                                                                                             
                                                                                                                                                        
          
                                                
                                                  
                                                  
                                     
                                          
                                          
                                                                 
                                                                                                                                                                                              
                                               
                                                  
                                                  
                                                         
                                                         
                                                 
                                             
                                                             
                                                                     
                                                                                                                                          
                                                                                                                                                                
                                                                                               
                                              
                                                                                                                                        
                                                                                                                                          
                                                                                    
                                                                                                                                         
                                                                                                   
                                                                                      
          
                                                                                                                                                  
                                                                                              
                                                                                                                                                                         
                                                                                                                                      
                                                                                                                           
                                                                                                                
                                                              
                                   
                                                                                                       
                       
 
                             
                                                                      
                                               
                                                                                                             
                                                                                    
                                                                                 
                                                
                                
                                                                                                                       
                                                                            
                                                                                                                                                  
                                                                                                                                                                           
                                                                                                  
 
                               
                                                                                                                                                                                                                                                                                        
                                     
                                                                                                        
                                                                                           
                                                                                                     
                                                                                              
                                                                                                                         
                                                                                                                                                                                                                                                                           
                                                                             
                                                                                        
                                                                                                    
 





/* ============ TEMPORARY ============ */
globalThis.ttimer = undefined;$('tq').addEventListener('input',e=>{clearTimeout(ttimer);ttimer=setTimeout(()=>searchTemp(e.target.value),220);});
                                                                                                                                               
                                                                                                                                                                                              
                                           
                            
                                                                                   
                                                                                              
                                                   
                                                                                                                                                                                         
                                                                                                
                                                                                                                            
                                                                                                                                                                                                      
                                                                                                                                                                                                                                                 
                                                                                                  
                                                                                                                                                             
                                                                                    
                                                                                      
                                                                                                            
                                                                                                                                                                                  
                                                                                              
                                                                                                                                              
                                                                                                                                                                                                                                                   
                                    
                                                                                             
                     
                                                                                                            
                                                                                                                                                                                                                              
                                            
                                                                                           
                                                                                            
                                                                                                                                                                                                                                                         
                                                                                                                                        
                                                                               
 

/* ============ ROUTE MAP ============ */
                              
                                                                                                                      
                                                                              
                                                                  
                                                                                                                                                                             
                                                                                                                                                                                 
                                                                                                                                                                                                                               
                                            
                                                   
                                           
                                                                                                                                                                                                  
                                                                                                                                                         
                                                                         
                        
                                                                                                                   
                                                                                                 
                                                                                                                                                                    
                                                                
                          
                                                                                                                           
                                                                                                                             
                                                                                                                    
                                                                                                                                                                                                                                                                                  
                                                                                                          
                                                                                                                                  
                                                                                        
                                                                                 
                                                                                    
                                                                    
                                                                                                         
                                                                                                                                            
                    
                                                                                                                                                                                                                                                                    
                     
                                                                     
                                                                                                                                                                                              
                         
                                                                                                                 
                                                                              
                                                                                                                                                                        
                                                                                                                                                                                     
                
                                                                                                                                                                       
                                             
 
                                                                                                                                                                                          
                                                                                                                    
                                                                  
                                                                                                                                                                  
                                
                                              
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                
/* use the saved pickup_order if present, else compute NN+2opt */
                                          
                                                  
                                                                                                                        
                                          
                                                                                          
                                                                                                                                                                                                                         
                                                                                                                                                                               
                                
 

/* ============ BULK ============ */
                      
                                                                                                                 
                                                                           
                                                                                                             
                                                                                                    
                                                                                                                                                                                                                                                                                                  
                        
                                                                                                                                            
                                                                           
            
                                                                                           
                                                                          
                                                     
                                                    
          
                                                                                                                             
                                                                 
                                                                                                                                                                                  
                                                   
                                              
                               
                                                                             
                                                                                       
                                                                                          
                         
                                                                                                  
            
                                                                      
                                                                                                     
                                                      
                                                     
            
                  
                                                                                                           
                                   
                                                          
                                                                      
                                                                                                  
                                                                                
                                                                                                                      
                                                                                                                                                     
                                                                                     
                                                                         
                                                                                        
                                                              
                                                                                                                          
                                                                                                                                                         
                                                                                                
                                                                   
                                                                                                        
                                                                                                                                   
                                                                
                                 
                                                                                                                                                                                                                                                                                                     
                              
                                
                                                                            
    
                                 
                                                                                                  
                          
                                                                                                                    
                                                                                                              
                                                       
                                                 
                                                           
                                                                                                                                                                        
                                                              
    
 

/* ============ CSV UPLOAD ============ */
globalThis.CSV_HINTS = {
  profiles:'Expected columns (header names are matched loosely): SR No, Student Name, Father\u2019s Name, Mother\u2019s Name, Date of Birth, Father\u2019s Mobile No, Mother\u2019s Mobile No, Class, Section, Gender, Home Address, Date of Admission, Previous School Name. Dates as DD-MM-YYYY. Rows are matched to students by SR No and stored as their profile.',
  pickup:'Expected columns: sr_no, seating_order (or pickup_order), bus_no. Each student\u2019s pickup position on their bus is set from this file.',
  busdetails:'Expected columns: bus_id, driver_name, driver_phone, conductor_name, conductor_phone, vehicle_no, model.'
};
                                                                                          
                                                                              
                                                        
                                                                                                                         
              
 
                                                                                                                           
                                                                                             
                                                                                             
globalThis.csvRows = null;

                                                                                          
                                                                              
                                                        
                                                                                                                         
              
 
                                                                                                                           
                                                                                             
                                                                                             
globalThis.csvKind = 'profiles';
                         
                                                                                             
                                                              
        
                            
                                            
                                              
                                                                 
                                                               
                                                              
                                                                                                                                
        
    
                              
 
                                                                 
                          
                                  
                                  
                                                               
                          
                                                                                       
   
              
 
                          
                                                                          
                                                     
      
                             
                                  
                                                     
                                                                     
                                                                                          
                                                                                          
                                                                      
                                                                                                           
                                                                                                           
                                                                                           
                                                                        
                                                                                                 
                                                                                             
                             
                                                                                              
                                                                              
                                                                              
                                                                                                                                                                       
                                                              
     
                                
                                  
                                                     
                                                                                                                
                                                                        
                                                
                                                                                                             
                                                                            
                                                                         
                                                                                                     
                        
                           
                                                                                                               
                                                                                                           
                                                             
                                                      
       
                                                                                                                                                                             
                                                                    
     
                                    
                                  
                                                                            
                                                                                                                          
                                                                                                                                            
                                                                                           
                                      
                                                                                             
                                                                          
                                                                                                              
                                                
     
                                                                                                                                                          
                            
 

/* ============ REPORTS (analytical) ============ */
globalThis.rupee = n=>'₹'+Math.round(Number(n||0)).toLocaleString('en-IN');
                                   
                                                              
                                                                                                                            
                                                                                                                                                                                  
                                                                                                                                                                                                     
 
                                                                                                                           
globalThis.repHeat = null;

                                   
                                                              
                                                                                                                            
                                                                                                                                                                                  
                                                                                                                                                                                                     
 
                                                                                                                           
globalThis.repHeatMode = 'students';
                               
                                                                                     
                                                                                                                                                                                                                      
                                      
                                                                                                                                                                
          
                                                     
                                        
                                                                                                                            
                                
 
                                 
                                                                             
                                
                                                    
                                                          
                                                                                  
                                                                 
                                                                                   
                                                                                      
                                                            
                                                                      
                                                                        
                                                                                                                                                
                                                                                                 
                                                                                      
                                                                                                                                           
   
                              
                                                    
                                                              
                                                                                          
                                                                 
                                                       
                                                                       
                                                             
                                                                   
                                                                                                   
                                                                                                    
                                                                                                                                                      
                                                                                                     
                                                                             
                                                                                     
   
                             
                                                                        
                                                                 
                                                                   
                                                                      
                                                                  
                                                       
                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
   
                                  
                                                    
                                                             
                                                                                      
                                                                                                                                                                                                                                                                                                               
                                                    
                                                                                            
                                                                                     
                                                                      
                                                                        
                                                                                                        
                                                                                                                                                                                                                                                 
                                                                                                                  
                                                                                          
                                                                
                                                                        
                                                                                                            
   
                               
                                                                                                                                     
                                                     
                                                                                     
                                                                                    
                                                                                                 
                                                                                        
                                                                                                                                                             
                                   
                                        
   
                                                                                                                                                                 
 
                                   
                                                                                                                                                  
                                                                                                                                                  
 
globalThis.repMap = null;

                               
                                                                                     
                                                                                                                                                                                                                      
                                      
                                                                                                                                                                
          
                                                     
                                        
                                                                                                                            
                                
 
                                 
                                                                             
                                
                                                    
                                                          
                                                                                  
                                                                 
                                                                                   
                                                                                      
                                                            
                                                                      
                                                                        
                                                                                                                                                
                                                                                                 
                                                                                      
                                                                                                                                           
   
                              
                                                    
                                                              
                                                                                          
                                                                 
                                                       
                                                                       
                                                             
                                                                   
                                                                                                   
                                                                                                    
                                                                                                                                                      
                                                                                                     
                                                                             
                                                                                     
   
                             
                                                                        
                                                                 
                                                                   
                                                                      
                                                                  
                                                       
                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
   
                                  
                                                    
                                                             
                                                                                      
                                                                                                                                                                                                                                                                                                               
                                                    
                                                                                            
                                                                                     
                                                                      
                                                                        
                                                                                                        
                                                                                                                                                                                                                                                 
                                                                                                                  
                                                                                          
                                                                
                                                                        
                                                                                                            
   
                               
                                                                                                                                     
                                                     
                                                                                     
                                                                                    
                                                                                                 
                                                                                        
                                                                                                                                                             
                                   
                                        
   
                                                                                                                                                                 
 
                                   
                                                                                                                                                  
                                                                                                                                                  
 
globalThis.repStudentPts = [];

                               
                                                                                     
                                                                                                                                                                                                                      
                                      
                                                                                                                                                                
          
                                                     
                                        
                                                                                                                            
                                
 
                                 
                                                                             
                                
                                                    
                                                          
                                                                                  
                                                                 
                                                                                   
                                                                                      
                                                            
                                                                      
                                                                        
                                                                                                                                                
                                                                                                 
                                                                                      
                                                                                                                                           
   
                              
                                                    
                                                              
                                                                                          
                                                                 
                                                       
                                                                       
                                                             
                                                                   
                                                                                                   
                                                                                                    
                                                                                                                                                      
                                                                                                     
                                                                             
                                                                                     
   
                             
                                                                        
                                                                 
                                                                   
                                                                      
                                                                  
                                                       
                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
   
                                  
                                                    
                                                             
                                                                                      
                                                                                                                                                                                                                                                                                                               
                                                    
                                                                                            
                                                                                     
                                                                      
                                                                        
                                                                                                        
                                                                                                                                                                                                                                                 
                                                                                                                  
                                                                                          
                                                                
                                                                        
                                                                                                            
   
                               
                                                                                                                                     
                                                     
                                                                                     
                                                                                    
                                                                                                 
                                                                                        
                                                                                                                                                             
                                   
                                        
   
                                                                                                                                                                 
 
                                   
                                                                                                                                                  
                                                                                                                                                  
 
globalThis.repRoutePts = [];
                                
                                                                                                                
                          
                                             
                                                                                   
                                                                                            
                                                                                    
                                                                                                             
                 
                                                                                                    
                                                                                                                                                                                                
                       
                                                                                                                                                                                                 
                                                               
                                                                                                   
                                                                                                                                            
                                                                                                                                               
 
                        
                         
                                                        
                                                      
                                                                                           
 

/* ============ ASK (AI / GIS quick questions) ============ */
globalThis.QUESTIONS = [
  {q:'Which buses exceed capacity?',run:async()=>{const {data}=await db.from('bus_economics').select('bus_id,students,capacity').order('bus_id');
    const over=(data||[]).filter(r=>r.students>r.capacity);return table(['bus_id','students','capacity'],over.map(r=>({...r})),over.length?'':'No bus is over capacity.');}},
  {q:'Students within 2 km of a bus’s route…',ask:'Bus number',run:async(bus)=>{const {data,error}=await db.rpc('students_near_bus_route',{p_bus:parseInt(bus,10),p_metres:2000});
    if(error)return '<div class="note">'+esc(error.message)+'</div>';return table(['sr_no','student_name','current_bus','metres_from_route'],data||[],'None found.');}},
  {q:'Which temporary buses expire tomorrow?',run:async()=>{const {data}=await db.from('alerts').select('*').eq('kind','temp_ending');return table(['subject','detail'],data||[],'None expiring tomorrow.');}},
  {q:'Nearest buses to a location…',ask:'lat,lon (e.g. 27.60,75.14)',run:async(v)=>{const [la,lo]=v.split(',').map(Number);const {data,error}=await db.rpc('nearest_buses_to_point',{p_lat:la,p_lon:lo,p_n:5});if(error)return esc(error.message);return table(['bus_id','km','riders','capacity'],data||[]);}},
  {q:'Duplicate / shared pickup locations',run:async()=>{const {data}=await db.rpc('duplicate_pickup_locations');return table(['n','students'],(data||[]).slice(0,50),'None.');}},
  {q:'Suggest where to move students off an overloaded bus…',ask:'Bus number',run:async(bus)=>{const {data,error}=await db.rpc('students_near_bus_route',{p_bus:parseInt(bus,10),p_metres:1500});
    if(error)return esc(error.message);
    return '<div class="note" style="margin-bottom:8px">Students of other buses within 1.5 km of Bus '+esc(bus)+'’s route — candidates to absorb its overflow, or to move its students onto:</div>'+table(['sr_no','student_name','current_bus','metres_from_route'],(data||[]).slice(0,40),'None nearby.');}},
];
                                                                                                             
                                                                                                                                                                                                                                                                                                                                          
/* ============ ADMISSION WIZARD / GEOGRAPHIC SUGGESTIONS ============ */
globalThis.admap = undefined;

                                                                                                             
                                                                                                                                                                                                                                                                                                                                          
/* ============ ADMISSION WIZARD / GEOGRAPHIC SUGGESTIONS ============ */
globalThis.adpin = undefined;

                                                                                                             
                                                                                                                                                                                                                                                                                                                                          
/* ============ ADMISSION WIZARD / GEOGRAPHIC SUGGESTIONS ============ */
globalThis.adReady = false;
                           
                                                                                                             
                        
                                                                                                                                                                                        
                                                                                                    
                                            
                                                                                 
                                                                                                         
                                             
 
                                                                                              
                                                                                                                                             
                                                                                                   
                                
                                                                                                     
                                                                               
                                                                                          
                                                                                                  
                                                                                                                          
                                                                                                                                                                                                                                                         
                 
                                                                                                                                                                                
                                                                                                          
                                                                                                                                      
                                                                                          
                                             
                                                 
                                                                                          
                                                       
                                                                                              
                                                                         
            
                                                                                                                                                                                                            
                      
                                                                                                    
 
                                  
                                                                                                 
                                                            
                                                                                                                                                                 
                                                                                                                                                          
                                                                   
 

/* ============ BUS PAGE ============ */
                               
                                                                                           
                                                                       
                                                                                                                        
                             
                                                                     
                                             
 
                                
                                                           
                                                                             
                                                                  
                                                                        
                                                                      
                                                                                                                                                   
                  
                                                                           
                                                                                                  
                                                                                                                                                                                                                                
                         
                                                  
                                                                                                                   
                                                                         
                                                                                                                         
                                                                                                                                
                                                                                     
                                                                                                                                                                                                                                                   
                                                                                                                                       
          
                                                                                                              
                                                                                                                                                                                                                       
                                
                                                                                                                                                                   
                                                           
                                                                                     
 

// small gazetteer of Sikar-area places so "near Piprali" resolves without a geocoding key
globalThis.PLACES = {piprali:[27.610,75.146],'radha kishanpura':[27.60,75.16],nawalgarh:[27.85,75.27],
  fatehpur:[27.99,74.96],reengus:[27.36,75.60],'sikar city':[27.61,75.14],khatushyamji:[27.39,75.42],
  ramgarh:[27.25,75.17],losal:[27.40,74.92],dhod:[27.50,75.13],palsana:[27.42,75.24]};
                     
                                 
                                        
                                                         
                                                                                       
                   
                                                                             
                                                                    
                                                                                           
                                                             
                                
                                                                                                                             
                                                                               
                                                                       
   
                                               
                                 
                                                                                                                                                          
                                                                                                                                                  
   
                                         
                                                                                                
                                                                                                    
                                         
                                                                                                                                                   
              
 
                                                                                                                                
                     
                                                                      
                                                                                                                                                               
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                  
                                                                                                                                        
                                                                                                                     
                                                   
                                                                        
                                                                                    
                                                                                                                                                                                                                                              
                                                                                                                                      
                                                                                                        
                                                                                                       
                                                      
                                                                                                   
 
// Only enter the app when a real session exists; otherwise the login gate stays
// visible. (A previous build called start() unconditionally here, which showed
// the app shell as the anon role — every data query then returned 0 rows.)
window.addEventListener("DOMContentLoaded", async () => {
    const { data } = await db.auth.getSession();
    if (data.session) start();
});

Object.assign(globalThis, { $, CSV_HINTS, GOOGLE_MAPS_API_KEY, PLACES, QUESTIONS, SUPABASE_KEY, SUPABASE_URL, adReady, admap, adpin, allMaps, buses, checkedBuses, colorOf, csvKind, csvRows, current, db, esc, googleFailed, googleLayers, googleReady, map, mapLayers, mapReady, pin, repHeat, repHeatMode, repMap, repRoutePts, repStudentPts, routeMap, rs, rupee, school, stimer, ttimer });
