// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

export function parseAsk(q){
  const t=q.toLowerCase().trim();
  const busM=t.match(/bus\s*(\d{1,2})/);
  const place=Object.keys(PLACES).find(p=>t.includes(p));
  const kmM=t.match(/(\d+(?:\.\d+)?)\s*km/); const km=kmM?parseFloat(kmM[1])*1000:2000;
  // intent routing
  if(/exceed|over ?capacity|overload/.test(t)) return {run:QUESTIONS[0].run};
  if(/expir|ending|tomorrow/.test(t)) return {run:QUESTIONS[2].run};
  if(/duplicate|same (stop|location|pickup)|shared/.test(t)) return {run:QUESTIONS[4].run};
  if(place && /which bus|buses (near|go|pass)|near/.test(t)){
    const [la,lo]=PLACES[place];
    return {run:async()=>'<div class="note" style="margin-bottom:8px">Buses whose routes pass nearest '+esc(place)+':</div>'+
      table(['bus_id','walk_metres','km_to_school','seats_left','recommended'],
        await rpc('suggest_bus_for_point',{p_lat:la,p_lon:lo,p_n:6}))};
  }
  if(busM && /shift|move|near|within/.test(t)){
    const b=parseInt(busM[1],10);
    return {run:async()=>'<div class="note" style="margin-bottom:8px">Students within '+(km/1000)+' km of Bus '+b+'’s route (candidates to shift):</div>'+
      table(['sr_no','student_name','current_bus','metres_from_route'],(await rpc('students_near_bus_route',{p_bus:b,p_metres:km})).slice(0,50))};
  }
  if(busM){ const b=parseInt(busM[1],10);
    return {run:async()=>{const {data}=await db.from('bus_capacity').select('*').eq('bus_id',b);
      return table(['bus_id','capacity','effective_capacity','riders'],data||[],'No such bus.');}};}
  if(place){ const [la,lo]=PLACES[place];
    return {run:async()=>table(['bus_id','walk_metres','seats_left','recommended'],await rpc('suggest_bus_for_point',{p_lat:la,p_lon:lo,p_n:5}))};}
  return null;
}

export async function rpc(fn,args){const {data,error}=await db.rpc(fn,args);if(error){console.error(error);return [];}return data||[];}

export function renderAsk(){
  $('askBody').innerHTML=`<h2 style="margin:0 0 6px">Ask the data</h2>
    <div class="note" style="margin-bottom:12px">Ask in your own words, or tap a question below. Every answer runs a live PostGIS query on your database.</div>
    <div style="display:flex;gap:8px;margin-bottom:6px"><input id="askBox" placeholder="e.g. Which buses go near Piprali?  ·  Which students can be shifted to Bus 18?" autocomplete="off"/><button class="b-signal" id="askGo">Ask</button></div>
    <div class="note" style="margin-bottom:16px">Understood examples: "buses near Piprali", "students within 2 km of Bus 17", "which buses exceed capacity", "duplicate pickup locations", "temp buses expiring tomorrow". Fully open-ended questions need the AI edge function (see notes).</div>
    <div style="font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--slate);margin-bottom:8px">Quick questions</div>
    <div id="qList">${QUESTIONS.map((x,i)=>`<button class="qbtn" data-i="${i}">${esc(x.q)}</button>`).join('')}</div>
    <div id="qOut" style="margin-top:14px"></div>`;
  const runFree=async()=>{const q=$('askBox').value.trim();if(!q)return;
    const parsed=parseAsk(q);$('qOut').innerHTML='<div class="hint">Working…</div>';
    if(!parsed){$('qOut').innerHTML='<div class="note">I couldn’t map that to a query yet. Try naming a bus number or a place (e.g. Piprali), or use a quick question. Open-ended natural language needs the AI edge function.</div>';return;}
    try{$('qOut').innerHTML=await parsed.run();}catch(e){$('qOut').innerHTML='<div class="note">'+esc(e.message||'error')+'</div>';}};
  $('askGo').onclick=runFree;$('askBox').addEventListener('keydown',e=>{if(e.key==='Enter')runFree();});
  [...$('qList').children].forEach(b=>b.onclick=async()=>{const x=QUESTIONS[+b.dataset.i];let arg=null;
    if(x.ask){arg=prompt(x.ask);if(arg===null)return;}
    $('qOut').innerHTML='<div class="hint">Running…</div>';$('qOut').innerHTML=await x.run(arg);});
}

Object.assign(globalThis, { parseAsk, rpc, renderAsk });
