// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

export function renderBulk(){
  // Round 2 children live in students_round2; this tool writes to `students`, so in Round 2
  // it would match nothing and cheerfully report "Moved 0". Say so instead.
  if(globalThis.tdRound===2){
    $('bulkBody').innerHTML=`<h2 style="margin:0 0 12px">Bulk operations</h2>
      <div class="databanner warn" style="max-width:680px">
        <span><b>Bulk operations are Round&nbsp;1 only.</b> Round&nbsp;2 children are held in their own
        table, and the impact analysis is built on the Round-1 routes. Switch to Round&nbsp;1 in the
        header, or move a Round-2 child from their profile on the Students tab.</span></div>`;
    return;
  }
  // An empty fleet list means the bus query failed at sign-in; without this the picker
  // renders with zero options and the chosen bus parses as NaN.
  if(!Array.isArray(buses) || !buses.length){
    $('bulkBody').innerHTML=`<h2 style="margin:0 0 12px">Bulk operations</h2>
      <div class="databanner bad" style="max-width:680px">
        <span><b>The bus list did not load.</b> Every bus picker would be empty, so moving students
        is disabled. Reload the page and sign in again.</span></div>`;
    return;
  }
  const opts=buses.map(b=>`<option value="${b.bus_id}">Bus ${b.bus_id} (${b.capacity} seats)</option>`).join('');
  $('bulkBody').innerHTML=`<h2 style="margin:0 0 12px">Bulk operations</h2>
    <div style="background:#fff;border:1px solid var(--edge);border-radius:8px;padding:16px;max-width:680px">
      <h3 style="margin:0 0 8px;font-size:15px">Permanently change the bus of selected students</h3>
      <div class="note" style="margin-bottom:12px">Add students by SR number, pick the new bus, then <b>Analyse impact</b> to see exactly what changes — capacity on every affected bus, route length, and annual fuel — before you commit. Pickup order on the old and new routes is reset.</div>
      <div class="grid">
        <div><label>Add students (SR numbers, comma or space separated)</label><input id="mvSrs" placeholder="e.g. 4542, 3073, 5044"/></div>
        <div><label>New bus</label><select id="mvTo">${opts}</select></div>
      </div>
      <div class="actions"><button class="b-primary" id="mvAnalyse">Analyse impact</button>
        <button class="b-signal" id="mvApply" disabled>Apply move</button>
        <span class="note" id="mvState"></span></div>
      <div id="mvOut" style="margin-top:12px"></div>
    </div>
    <div style="background:#fff;border:1px solid var(--edge);border-radius:8px;padding:16px;max-width:680px;margin-top:16px">
      <h3 style="margin:0 0 8px;font-size:15px">Upload a CSV</h3>
      <div class="note" style="margin-bottom:12px">Upload straight into the database from here. Pick what the file contains, choose the file, preview the match, then apply.</div>
      <div class="grid" style="margin-bottom:10px">
        <div><label>This file contains</label>
          <select id="csvKind">
            <option value="profiles">Student profiles (whole school)</option>
            <option value="pickup">Pickup order (sr_no, seating_order, bus_no)</option>
            <option value="busdetails">Bus details (driver / conductor / vehicle)</option>
          </select></div>
        <div><label>CSV file</label><input type="file" id="csvFile" accept=".csv,text/csv"/></div>
      </div>
      <div id="csvHint" class="note" style="margin-bottom:10px"></div>
      <div class="actions"><button class="b-primary" id="csvGo" disabled>Preview &amp; apply</button>
        <span class="note" id="csvState"></span></div>
      <div id="csvOut" style="margin-top:12px"></div>
    </div>`;
  bindCsvUpload();
  const parseSrs=()=>[...new Set(($('mvSrs').value||'').split(/[\s,]+/).map(x=>x.trim()).filter(Boolean))];
  $('mvAnalyse').onclick=async()=>{
    const srs=parseSrs(), to=parseInt($('mvTo').value,10);
    if(!srs.length){toast('Add at least one SR number','bad');return;}
    $('mvOut').innerHTML='<div class="hint">Calculating impact…</div>';$('mvApply').disabled=true;
    const {data,error}=await db.rpc('move_students_impact',{p_srs:srs,p_to:to});
    if(error){$('mvOut').innerHTML='<div class="note" style="color:var(--stop)">'+esc(error.message)+'</div>';return;}
    if(!data||!data.length){$('mvOut').innerHTML='<div class="note">No matching students with coordinates found for those SR numbers.</div>';return;}
    const tgt=data.find(r=>r.role==='target'), src=data.filter(r=>r.role==='source');
    const netFuel=data.reduce((a,r)=>a+Number(r.delta_annual_fuel||0),0);
    const rupee=n=>((n>=0?'+':'−')+'₹'+Math.abs(Math.round(n)).toLocaleString('en-IN'));
    const km=n=>((n>=0?'+':'−')+Math.abs(n).toFixed(2)+' km');
    let html=`<div style="background:#fff;border:1px solid var(--edge);border-radius:8px;overflow:auto"><table><thead><tr>
      <th>Bus</th><th>Role</th><th>Students</th><th>Riders now → after</th><th>Effective cap</th><th>Route Δ</th><th>Fuel/yr Δ</th></tr></thead><tbody>`;
    const rowHtml=r=>`<tr${r.role==='target'&&r.over_capacity?' style="background:#fdecea"':''}>
      <td>Bus ${r.bus_id}</td><td>${r.role}</td><td>${r.moved}</td>
      <td>${r.current_riders} → ${r.new_riders}${(r.role==='target'&&r.over_capacity)?' ⚠ OVER':''}</td>
      <td>${r.effective_capacity}</td><td>${km(Number(r.delta_route_km))}</td><td>${rupee(Number(r.delta_annual_fuel))}</td></tr>`;
    if(tgt)html+=rowHtml(tgt); src.forEach(r=>html+=rowHtml(r));
    html+=`</tbody></table></div>
      <div class="note" style="margin-top:10px">Net fleet fuel change: <b>${rupee(netFuel)}</b> per year.${tgt&&tgt.over_capacity?' <span style="color:var(--stop)">Target bus would exceed its effective capacity.</span>':''} Route and fuel figures are estimates from the current routes.</div>`;
    $('mvOut').innerHTML=html;
    $('mvApply').disabled=false;
    $('mvApply').dataset.srs=JSON.stringify(srs);$('mvApply').dataset.to=to;
  };
  $('mvApply').onclick=async()=>{
    const srs=JSON.parse($('mvApply').dataset.srs||'[]'), to=parseInt($('mvApply').dataset.to,10);
    if(!srs.length)return;
    if(!Number.isFinite(to)){toast('Pick a bus first','bad');return;}
    if(!confirm(`Permanently move ${srs.length} student(s) to Bus ${to}? Their pickup order will be reset.`))return;
    // .eq('active',true) — without it a student who has left the school is silently moved
    // back onto a live roster. .select() returns the rows actually written, which is the
    // only trustworthy count: a mistyped SR matches nothing and reports no error at all.
    const {data,error}=await db.from('students')
      .update({bus_no:to,pickup_order:null,updated_by:'bulk_move'})
      .in('sr_no',srs).eq('active',true).select('sr_no,name');
    if(error){toast(error.message,'bad');return;}
    const moved=(data||[]).map(r=>String(r.sr_no));
    const missed=srs.filter(x=>!moved.includes(String(x)));
    if(!moved.length){
      toast('Nothing moved — no active student matched those SR numbers','bad');
      $('mvOut').innerHTML=`<div class="databanner bad"><span><b>Nothing was moved.</b> None of these
        SR numbers matched an active Round-1 student: ${esc(srs.join(', '))}</span></div>`;
      return;
    }
    toast(`Moved ${moved.length} student(s) to Bus ${to}`,'good');
    $('mvOut').innerHTML=`<div class="databanner ${missed.length?'warn':''}" style="${missed.length?'':'background:var(--ok-bg);border:1px solid #b7dfc9;color:#14532d'}">
      <span><b>Moved ${moved.length} of ${srs.length}</b> to Bus ${to}. Set their pickup positions on the Pickup order tab.
      ${missed.length?`<br><b>Not moved (${missed.length}):</b> ${esc(missed.join(', '))} — not an active Round-1 SR.`:''}</span></div>`;
    $('mvApply').disabled=true;mapReady=false;loadDashboard();
  };
}

export function bindCsvUpload(){
  const upd=()=>{ csvKind=$('csvKind').value; $('csvHint').textContent=CSV_HINTS[csvKind]; };
  $('csvKind').onchange=()=>{upd();$('csvOut').innerHTML='';};
  upd();
  $('csvFile').onchange=e=>{
    const f=e.target.files[0]; if(!f)return;
    $('csvState').textContent='Reading\u2026';
    Papa.parse(f,{header:true,skipEmptyLines:true,complete:res=>{
      csvRows=res.data; $('csvGo').disabled=csvRows.length===0;
      $('csvState').textContent=`${csvRows.length} rows read`;
      $('csvOut').innerHTML=`<div class="note">Columns found: ${Object.keys(csvRows[0]||{}).map(esc).join(', ')||'none'}</div>`;
    }});
  };
  $('csvGo').onclick=applyCsv;
}

export async function chunkUpsert(table, rows, opts){ // opts.onConflict
  let done=0; const N=200;
  for(let i=0;i<rows.length;i+=N){
    const slice=rows.slice(i,i+N);
    const {error}=await db.from(table).upsert(slice, opts||{});
    if(error) throw error;
    done+=slice.length; $('csvState').textContent=`Saved ${done}/${rows.length}\u2026`;
  }
  return done;
}

export async function applyCsv(){
  if(!csvRows||!csvRows.length){toast('Choose a CSV first','bad');return;}
  $('csvGo').disabled=true; $('csvOut').innerHTML='';
  try{
    if(csvKind==='profiles'){
      const recs=csvRows.map(r=>({
        sr_no: pick(r,['sr_no','sr no','srno','sr']),
        student_name: pick(r,['student_name','student name','name']),
        father_name: pick(r,["father's name",'father name','father_name','fathers name']),
        mother_name: pick(r,["mother's name",'mother name','mother_name','mothers name']),
        dob: isoDate(pick(r,['date of birth','dob','date_of_birth'])),
        father_phone: digits(pick(r,["father's mobile no",'father mobile','father_phone','father phone'])),
        mother_phone: digits(pick(r,["mother's mobile no",'mother mobile','mother_phone','mother phone'])),
        class: pick(r,['class']), section: pick(r,['section']), gender: pick(r,['gender']),
        home_address: pick(r,['home address','home_address','address']),
        admission_date: isoDate(pick(r,['date of admission','admission date','admission_date'])),
        previous_school: pick(r,['previous school name','previous school','previous_school'])
      })).filter(x=>x.sr_no);
      if(!recs.length){toast('No SR No column found','bad');$('csvGo').disabled=false;return;}
      const n=await chunkUpsert('student_profiles',recs,{onConflict:'sr_no'});
      // also backfill parent/phone on transport students for the panel fields
      $('csvOut').innerHTML=`<div class="note" style="color:var(--good)">Saved ${n} student profiles. Transport students will show these on their profile card.</div>`;
      toast(`Uploaded ${n} profiles`,'good'); loadDashboard();
    }
    else if(csvKind==='pickup'){
      const rows=csvRows.map(r=>({
        sr_no: pick(r,['sr_no','sr no','srno','sr']),
        order: parseInt(pick(r,['seating_order','pickup_order','seating order','pickup order','order'])||'',10),
        bus: parseInt(pick(r,['bus_no','bus','bus_id','bus no'])||'',10)
      })).filter(x=>x.sr_no && !isNaN(x.order));
      if(!rows.length){toast('Need sr_no and seating_order columns','bad');$('csvGo').disabled=false;return;}
      // clear affected buses' order first to avoid unique clashes, then set
      const busSet=[...new Set(rows.map(r=>r.bus).filter(b=>!isNaN(b)))];
      for(const b of busSet){ await db.from('students').update({pickup_order:null}).eq('bus_no',b); }
      let done=0,miss=0;
      for(const r of rows){
        const q=db.from('students').update({pickup_order:r.order,updated_by:'csv_upload'}).eq('sr_no',r.sr_no);
        const {error,count}=await (isNaN(r.bus)? q : q.eq('bus_no',r.bus)).select('sr_no',{count:'exact'});
        if(error) throw error; if(count) done++; else miss++;
        $('csvState').textContent=`Set ${done}\u2026`;
      }
      $('csvOut').innerHTML=`<div class="note" style="color:var(--good)">Set pickup order for ${done} students${miss?`; ${miss} SR not matched on the given bus`:''}.</div>`;
      toast(`Pickup order set for ${done}`,'good'); loadDashboard();
    }
    else if(csvKind==='busdetails'){
      const recs=csvRows.map(r=>({
        bus_id: parseInt(pick(r,['bus_id','bus','bus no','bus_no'])||'',10),
        driver_name: pick(r,['driver_name','driver name']), driver_phone: digits(pick(r,['driver_phone','driver phone'])),
        conductor_name: pick(r,['conductor_name','conductor name']), conductor_phone: digits(pick(r,['conductor_phone','conductor phone'])),
        vehicle_no: pick(r,['vehicle_no','vehicle no','vehicle']), model: pick(r,['model'])
      })).filter(x=>!isNaN(x.bus_id));
      if(!recs.length){toast('Need a bus_id column','bad');$('csvGo').disabled=false;return;}
      const n=await chunkUpsert('bus_details',recs,{onConflict:'bus_id'});
      $('csvOut').innerHTML=`<div class="note" style="color:var(--good)">Saved details for ${n} buses.</div>`;
      toast(`Uploaded ${n} bus records`,'good');
    }
  }catch(e){ $('csvOut').innerHTML=`<div class="note" style="color:var(--stop)">${esc(e.message||'Upload failed')}</div>`; toast('Upload failed','bad'); }
  $('csvGo').disabled=false;
}

Object.assign(globalThis, { renderBulk, bindCsvUpload, chunkUpsert, applyCsv });
