// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

import { insertTeachers } from "./teacherroute.js";
import { roundBusIds } from "./rounds.js";

export async function renderBusPage(){
  // Round 2 is run by a subset of the fleet, so only those buses belong in the picker
  const ids=await roundBusIds();
  const opts=ids.map(id=>`<option value="${id}">Bus ${id}</option>`).join('');
  if(!ids.length){$('busPageBody').innerHTML='<h2 style="margin:0 0 10px">Bus page</h2><div class="note">No buses run Round 2.</div>';return;}
  $('busPageBody').innerHTML=`<h2 style="margin:0 0 10px">Bus page</h2>
    <div style="max-width:220px;margin-bottom:16px"><label>Choose a bus</label><select id="bpSel">${opts}</select></div>
    <div id="bpBody"></div>`;
  $('bpSel').onchange=()=>loadBusPage(parseInt($('bpSel').value,10));
  loadBusPage(parseInt($('bpSel').value,10));
}

export async function loadBusPage(bus){
  $('bpBody').innerHTML='<div class="hint">Loading…</div>';
  if(globalThis.tdRound===2){
    const [{data:cap},{data:r2},{data:rt},{data:gj}]=await Promise.all([
      db.from('bus_capacity').select('*').eq('bus_id',bus).maybeSingle(),
      db.from('students_round2').select('sr_no,name,class,section,pickup_order').eq('bus_no',bus).eq('active',true)
        .order('pickup_order',{nullsFirst:false}),
      db.from('r2_route').select('*').eq('bus_id',bus).maybeSingle(),
      db.from('r2_route_geo').select('*').eq('bus_id',bus).maybeSingle()]);
    const kids=r2||[];
    const seats=cap?cap.capacity:null;
    const over=seats!=null&&kids.length>seats;
    const rws=kids.map(k=>`<tr><td>${k.pickup_order??'—'}</td><td>${esc(k.name)}</td><td class="mono">${esc(k.sr_no)}</td><td>${esc(k.class||'')}${k.section?'-'+esc(k.section):''}</td></tr>`).join('');
    $('bpBody').innerHTML=`
      <div class="cards" style="margin-bottom:16px">
        <div class="stat"><b>${kids.length}</b><span>Round 2 children</span></div>
        <div class="stat"><b>${seats??'—'}</b><span>Vehicle seats</span></div>
        ${over?`<div class="stat"><b style="color:var(--stop)">${kids.length-seats} over</b><span>Above seats</span></div>`
              :`<div class="stat"><b>${seats!=null?seats-kids.length:'—'}</b><span>Seats free</span></div>`}
        ${gj?`<div class="stat"><b>${Number(gj.road_km).toFixed(1)} km</b><span>Round trip from school</span></div>`:''}
        ${gj?`<div class="stat"><b>${gj.drive_min} min</b><span>Driving, excl. stops</span></div>`:''}
        ${rt&&rt.annual_fuel?`<div class="stat"><b>${rs(rt.annual_fuel)}</b><span>Annual fuel</span></div>`:''}</div>
      <h3 style="margin:0 0 8px;font-size:15px">Round 2 children on bus ${bus} (${kids.length}) — in driving order</h3>
      ${kids.length?`<div style="background:var(--panel);border:1px solid var(--edge);border-radius:8px;overflow:auto">
        <table><thead><tr><th>#</th><th>Name</th><th>SR</th><th>Class</th></tr></thead><tbody>${rws}</tbody></table></div>`
        :'<div class="note">This bus has no Round 2 children.</div>'}
      <div class="note" style="margin-top:10px">Round 2 leaves <b>from school</b> and returns to school, both morning and afternoon — there is no depot leg. The order above is the shortest loop through these children, solved and measured on <b>real roads</b> via Google Directions${gj&&gj.reordered?' (re-ordered from the earlier straight-line order, saving '+(Number(gj.seq_km)-Number(gj.road_km)).toFixed(2)+' km per trip)':''}. The driving time excludes the time the bus stands at each stop.</div>`;
    return;
  }
  const [{data:cap},{data:econ},{data:det},{data:roster},{data:fuelSh},{data:tchs}]=await Promise.all([
    db.from('bus_capacity').select('*').eq('bus_id',bus).single(),
    db.from('bus_economics').select('*').eq('bus_id',bus).maybeSingle(),
    db.from('bus_details').select('*').eq('bus_id',bus).maybeSingle(),
    db.from('bus_roster').select('sr_no,student_name,pickup_order,road_min_to_school,latitude,longitude,depot_lat,depot_lon,bus_has_depot').eq('bus_id',bus).order('pickup_order',{nullsFirst:false}),
    db.from('opt_student_fuel').select('sr_no,ride_km,ride_min,share_pct,fuel_share').eq('bus_id',bus),
    db.from('teachers').select('name,emp_code,latitude,longitude').eq('bus_no',String(bus)).order('name')]);
  const d=det||{};
  const stat=(l,v)=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`;
  const fld=(l,k)=>`<div><label>${l}</label><input id="bd_${k}" value="${esc(d[k]||'')}"/></div>`;
  // Salaries are monthly and maintenance is a yearly figure, so they are labelled as such
  // rather than silently mixed. Blank stays blank — never coerced to 0.
  const fldn=(l,k)=>`<div><label>${l}</label><input id="bd_${k}" type="number" min="0" step="1" value="${d[k]??''}"/></div>`;
  const staffYr=((+d.driver_salary||0)+(+d.conductor_salary||0))*12;
  const maintYr=+d.maintenance_cost||0;
  // Vehicle age is derived from the year of manufacture, never stored, so it cannot go stale.
  const age=d.model_year?(new Date().getFullYear()-d.model_year):null;
  const fuelBy={}; (fuelSh||[]).forEach(f=>fuelBy[f.sr_no]=f);
  // The morning run carries students AND teachers, so the driving order is the two merged:
  // each teacher sits at the point in the student sequence that adds the least distance.
  const r0=(roster||[])[0]||{};
  const depot=r0.bus_has_depot?[r0.depot_lat,r0.depot_lon]:null;
  const schoolPt=(typeof school!=='undefined'&&school)?[school.latitude,school.longitude]:null;
  const placeable=(roster||[]).filter(r=>r.latitude!=null);
  const unplaced=(roster||[]).filter(r=>r.latitude==null);   // no coordinates -> cannot be sequenced
  const morningSeq=insertTeachers(placeable,(tchs||[]),depot,schoolPt).seq;
  const studentCell=(r,f)=>`<td>${esc(r.student_name)}</td><td class="mono">${esc(r.sr_no)}</td><td>${f.ride_min!=null?f.ride_min+' min':(r.road_min_to_school!=null?r.road_min_to_school+' min':'—')}</td><td>${f.ride_km!=null?f.ride_km+' km':'—'}</td><td>${f.fuel_share!=null?rs(f.fuel_share)+'/yr':'—'}</td>`;
  const rows=morningSeq.map((r,i)=>{
    if(r.kind==='teacher')
      return `<tr style="background:#eef4ff"><td>${i+1}</td><td>🧑‍🏫 ${esc(r.name)}</td><td class="mono">${esc(r.emp_code||'—')}</td><td colspan="3" class="note">teacher — rides in only, not on the return trip</td></tr>`;
    return `<tr><td>${i+1}</td>${studentCell(r,fuelBy[r.sr_no]||{})}</tr>`;
  }).join('')
  + unplaced.map(r=>`<tr><td>—</td>${studentCell(r,fuelBy[r.sr_no]||{})}</tr>`).join('');
  $('bpBody').innerHTML=`
    <div class="cards" style="margin-bottom:16px">
      ${stat('Students',cap.riders)}${stat('Capacity',cap.capacity)}
      ${cap.riders>cap.capacity?stat('Over capacity (allowed)',cap.riders-cap.capacity):stat('Seats free',cap.capacity-cap.riders)}
      ${(tchs&&tchs.length)?stat('Morning load (with teachers)',`${cap.riders+tchs.length}/${cap.capacity}`):''}
      ${econ?stat('Road km/trip',econ.road_km_per_trip):''}${econ?stat('Annual fuel',rs(econ.annual_fuel_cost)):''}</div>
    <div style="background:#fff;border:1px solid var(--edge);border-radius:8px;padding:16px;margin-bottom:16px;max-width:760px">
      <h3 style="margin:0 0 10px;font-size:15px">Vehicle</h3>
      <div class="grid">${fld('Vehicle no.','vehicle_no')}${fld('Make','company')}${fldn('Year of manufacture','model_year')}
        <div><label>Age</label><input value="${age!=null?age+(age===1?' year':' years'):'—'}" disabled title="Worked out from the year of manufacture"/></div>
        ${fld('Route name','route_name')}</div>
      <h3 style="margin:16px 0 10px;font-size:15px">Driver &amp; conductor</h3>
      <div class="grid">${fld('Driver name','driver_name')}${fld('Driver phone','driver_phone')}${fldn('Driver salary — monthly','driver_salary')}
        ${fld('Conductor name','conductor_name')}${fld('Conductor phone','conductor_phone')}${fldn('Conductor salary — monthly','conductor_salary')}</div>
      <h3 style="margin:16px 0 10px;font-size:15px">Running cost</h3>
      <div class="grid">${fldn('Maintenance — this year','maintenance_cost')}</div>
      ${(staffYr||maintYr)?`<div class="note" style="margin-top:10px">Staff <b>${rs(staffYr)}</b>/yr (salaries &times; 12)${maintYr?` + maintenance <b>${rs(maintYr)}</b>/yr`:''}${econ&&econ.annual_fuel_cost?` + fuel <b>${rs(econ.annual_fuel_cost)}</b>/yr`:''} = <b>${rs(staffYr+maintYr+((econ&&+econ.annual_fuel_cost)||0))}</b> a year to run this bus.</div>`:''}
      ${d.conductor_name?'':'<div class="note" style="margin-top:8px">No conductor recorded on this bus.</div>'}
      <div class="actions"><button class="b-primary" id="bpSave">Save bus details</button><span class="note" id="bpState"></span></div>
    </div>
    ${(tchs&&tchs.length)?`<div style="background:var(--panel);border:1px solid var(--edge);border-radius:8px;padding:12px 16px;margin-bottom:16px">
      <h3 style="margin:0 0 6px;font-size:15px">Teachers riding this bus — mornings only (${tchs.length})</h3>
      <div style="display:flex;flex-wrap:wrap;gap:6px">${tchs.map(t=>`<span class="flag" style="background:#eef4ff;border-color:#c9dcf7;color:#1f4d8f">${esc(t.name)}${t.emp_code?' · '+esc(t.emp_code):''}</span>`).join('')}</div>
      <div class="note" style="margin-top:6px">They come to school with Round 1 and do not travel back with the students.</div></div>`:''}
    <h3 style="margin:0 0 8px;font-size:15px">Morning run — ${(roster||[]).length} student${(roster||[]).length===1?'':'s'}${(tchs&&tchs.length)?` + ${tchs.length} teacher${tchs.length===1?'':'s'}`:''}, in driving order</h3>
    <div style="background:#fff;border:1px solid var(--edge);border-radius:8px;overflow:auto"><table><thead><tr><th>#</th><th>Name</th><th>SR / Emp</th><th>Ride to school (along route)</th><th>Ride km</th><th>Fuel share</th></tr></thead><tbody>${rows}</tbody></table></div>
    ${(tchs&&tchs.length)?`<div class="note" style="margin-top:8px">Teachers are placed where they add the least distance to the existing student route. The afternoon run drops students only.</div>`:''}`;
  $('bpSave').onclick=async()=>{
    const rec={bus_id:bus};
    ['driver_name','driver_phone','conductor_name','conductor_phone','vehicle_no','company','route_name']
      .forEach(k=>rec[k]=$('bd_'+k).value.trim()||null);
    // A blank number must stay blank. Sending 0 would claim the bus costs nothing to run.
    ['model_year','driver_salary','conductor_salary','maintenance_cost'].forEach(k=>{
      const v=$('bd_'+k).value.trim(); rec[k]=v===''?null:Number(v);});
    if(rec.model_year!=null&&(rec.model_year<1990||rec.model_year>new Date().getFullYear()+1)){
      toast('Year of manufacture looks wrong','bad');return;}
    if(['driver_salary','conductor_salary','maintenance_cost'].some(k=>rec[k]!=null&&rec[k]<0)){
      toast('Costs cannot be negative','bad');return;}
    const {error}=await db.from('bus_details').upsert(rec);
    if(error){toast(error.message,'bad');return;}
    toast('Bus details saved','good'); loadBusPage(bus);};
}

Object.assign(globalThis, { renderBusPage, loadBusPage });
