// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

import { GOOGLE_MAPS_API_KEY } from "./config.js";

export function loadGoogle(){
  if(!GOOGLE_MAPS_API_KEY) return;
  const s=document.createElement('script');
  s.src=`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_MAPS_API_KEY}`;
  s.async=true;
  s.onload=()=>{googleReady=true; allMaps.forEach(attachGoogle);};
  s.onerror=()=>{googleFailed=true;};
  document.head.appendChild(s);
}

export function attachGoogle(m){
  if(!(GOOGLE_MAPS_API_KEY && googleReady && !googleFailed && window.google && window.google.maps
        && L.gridLayer && L.gridLayer.googleMutant)) return;
  try{const g=L.gridLayer.googleMutant({type:'roadmap',maxZoom:20});g.addTo(m);googleLayers.push(g);}catch(e){}
}

export function addBaseLayer(m){
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(m);
  allMaps.push(m); attachGoogle(m);
}

export function initEditMap(){
  map=L.map('map',{zoomControl:true}).setView([school?school.latitude:27.578,school?school.longitude:75.137],12);
  addBaseLayer(map);
  if(school)L.marker([school.latitude,school.longitude],{icon:L.divIcon({className:'',html:'<div style="font-size:22px">🏫</div>',iconSize:[22,22],iconAnchor:[11,11]})}).addTo(map).bindPopup('School');
  map.on('click',e=>{if(current)setPin(e.latlng.lat,e.latlng.lng,true);});
}

export function setPin(lat,lon,edit){
  if(!pin){pin=L.marker([lat,lon],{draggable:true}).addTo(map);pin.on('dragend',()=>{const p=pin.getLatLng();setPin(p.lat,p.lng,true);});}
  else pin.setLatLng([lat,lon]);
  if($('cLat')){$('cLat').textContent=lat.toFixed(6);$('cLon').textContent=lon.toFixed(6);}
  if(edit&&$('saveBtn'))$('saveBtn').disabled=false;
}

export async function openRouteMap(){
  if(!routeMap){routeMap=L.map('routemap').setView([school?school.latitude:27.578,school?school.longitude:75.137],11);
    addBaseLayer(routeMap);L.control.scale({imperial:false}).addTo(routeMap);}
  setTimeout(()=>routeMap.invalidateSize(),60);if(mapReady)return;
  const data=await fetchAll('bus_roster','sr_no,student_name,bus_id,pickup_order,latitude,longitude,depot_lat,depot_lon,bus_has_depot,road_km_to_school,road_min_to_school');
  const byBus={};data.forEach(s=>{if(s.latitude==null)return;(byBus[s.bus_id]=byBus[s.bus_id]||{stops:[],depot:s.bus_has_depot?[s.depot_lat,s.depot_lon]:null}).stops.push(s);});
  if(school)L.marker([school.latitude,school.longitude],{icon:L.divIcon({className:'',html:'<div style="font-size:22px">🏫</div>',iconSize:[22,22],iconAnchor:[11,11]}),zIndexOffset:1000}).addTo(routeMap).bindPopup('School');
  const leg=$('mapLegend');leg.innerHTML='';
  const busIds=Object.keys(byBus).sort((a,b)=>a-b);
  checkedBuses=new Set(busIds.map(String));
  const ctrl=document.createElement('div');ctrl.style.cssText='display:flex;align-items:center;gap:10px;padding:4px 4px 8px;border-bottom:1px solid var(--edge);margin-bottom:6px;font-size:12px';
  ctrl.innerHTML=`<label style="display:flex;align-items:center;gap:6px;cursor:pointer"><input type="checkbox" id="mapSelAll" checked> Select all</label>
    <a href="#" id="mapDesel" style="margin-left:auto">Deselect all</a>`;
  leg.appendChild(ctrl);
  busIds.forEach(bus=>{const col=colorOf[bus]||'#666';const g=L.layerGroup().addTo(routeMap);const info=byBus[bus];
    const order=orderStops(info.stops,info.depot,school?[school.latitude,school.longitude]:null);
    const path=[];if(info.depot)path.push(info.depot);order.forEach(s=>path.push([s.latitude,s.longitude]));if(school)path.push([school.latitude,school.longitude]);
    L.polyline(path,{color:col,weight:2.5,opacity:.8}).addTo(g);
    order.forEach((s,i)=>{
      const road = s.road_min_to_school!=null ? `${s.road_min_to_school} min · ${s.road_km_to_school} km by road to school`
                   : `${hav(s.latitude,s.longitude,school.latitude,school.longitude).toFixed(1)} km straight-line to school`;
      const m=L.circleMarker([s.latitude,s.longitude],{radius:6,weight:1,color:'#fff',fillColor:col,fillOpacity:1});
      m.bindPopup(`<b>${esc(s.student_name)}</b><br>Bus ${bus} · pickup #${i+1}<br><span class="mono">${esc(s.sr_no)}</span><br>${road}<br><a href="#" data-nearest="${s.latitude},${s.longitude}" data-bus="${bus}">Show this bus + 3 nearest ▾</a><div class="nearbox"></div>`);
      m.on('popupopen',ev=>{const el=ev.popup.getElement().querySelector('a[data-nearest]');if(!el)return;
        el.onclick=async(e)=>{e.preventDefault();const [la,lo]=el.dataset.nearest.split(',').map(Number);const cur=el.dataset.bus;
          const box=ev.popup.getElement().querySelector('.nearbox');box.textContent='…';
          const {data:n}=await db.rpc('assign_impact',{p_lat:la,p_lon:lo,p_n:5});
          const others=(n||[]).filter(r=>String(r.bus_id)!==String(cur)).slice(0,3);
          setCheckedBuses([Number(cur),...others.map(r=>r.bus_id)]);
          box.innerHTML=`<div style="margin-top:4px">Now showing 4 buses:</div>Bus ${cur} (current)<br>`+
            others.map(r=>`Bus ${r.bus_id} · ${r.detour_km} km detour · ${r.seats_left} seats${r.has_room?'':' (full)'}`).join('<br>');};});
      m.addTo(g);});
    if(info.depot)L.marker(info.depot,{icon:L.divIcon({className:'',html:`<div style="width:11px;height:11px;background:${col};border:2px solid #fff;transform:rotate(45deg)"></div>`,iconSize:[13,13],iconAnchor:[6,6]})}).addTo(g).bindPopup('Bus '+bus+' depot');
    mapLayers[bus]=g;
    const row=document.createElement('label');row.className='legrow';
    row.innerHTML=`<input type="checkbox" class="legchk" data-bus="${bus}" checked><span class="sw" style="background:${col}"></span>Bus ${bus}<span class="cnt">${info.stops.length}</span>`;
    leg.appendChild(row);
    row.querySelector('.legchk').onchange=e=>{e.stopPropagation();toggleBus(bus,e.target.checked);syncSelAll();};
    row.querySelector('.sw').onclick=e=>{e.preventDefault();isolate(bus);};});
  $('mapSelAll').onchange=e=>{const on=e.target.checked;busIds.forEach(b=>toggleBus(b,on));[...leg.querySelectorAll('.legchk')].forEach(c=>c.checked=on);on&&fitMap();};
  $('mapDesel').onclick=e=>{e.preventDefault();busIds.forEach(b=>toggleBus(b,false));[...leg.querySelectorAll('.legchk')].forEach(c=>c.checked=false);$('mapSelAll').checked=false;};
  mapReady=true;
  $('mapAll').onclick=()=>{busIds.forEach(b=>toggleBus(b,true));[...leg.querySelectorAll('.legchk')].forEach(c=>c.checked=true);$('mapSelAll').checked=true;fitMap();};
  $('mapFit').onclick=fitMapChecked;fitMap();
}

export function toggleBus(bus,on){const g=mapLayers[bus];if(!g)return;if(on){routeMap.addLayer(g);checkedBuses.add(String(bus));}else{routeMap.removeLayer(g);checkedBuses.delete(String(bus));}}

export function syncSelAll(){const sa=$('mapSelAll');if(sa)sa.checked=(checkedBuses.size===Object.keys(mapLayers).length);}

export function setCheckedBuses(ids){const want=new Set(ids.map(String));
  Object.keys(mapLayers).forEach(b=>{const on=want.has(String(b));toggleBus(b,on);const c=document.querySelector(`.legchk[data-bus="${b}"]`);if(c)c.checked=on;});
  syncSelAll();fitMapChecked();}

export function isolate(bus){setCheckedBuses([bus]);}

export function fitMapChecked(){const all=[];checkedBuses.forEach(b=>{const g=mapLayers[b];if(g)g.getLayers().forEach(l=>all.push(l));});if(all.length){const bb=L.featureGroup(all).getBounds();if(bb.isValid())routeMap.fitBounds(bb.pad(.15));}}

export function fitMap(){const all=[];Object.values(mapLayers).forEach(g=>g.getLayers().forEach(l=>all.push(l)));if(all.length){const b=L.featureGroup(all).getBounds();if(b.isValid())routeMap.fitBounds(b.pad(.1));}}

Object.assign(globalThis, { loadGoogle, attachGoogle, addBaseLayer, initEditMap, setPin, openRouteMap, toggleBus, syncSelAll, setCheckedBuses, isolate, fitMapChecked, fitMap });
