// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

export async function renderReports(){
  $('reportsBody').innerHTML=`<h2 style="margin:0 0 4px">Reports &amp; analytics</h2>
    <div class="note" style="margin-bottom:12px">Live analysis of the fleet, using the diesel price, working days and trips set in the parameters. Fuel and route numbers are model estimates; fees are actuals.</div>
    <div class="busbtns" id="repTabs">
      ${['Fuel efficiency','Capacity','Finance','Start points','Geography'].map((k,i)=>`<button data-r="${k}" class="${i===0?'on':''}">${k}</button>`).join('')}
    </div>
    <div id="repOut" style="margin-top:16px"></div>`;
  const tabs=[...$('repTabs').children];
  tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.remove('on'));b.classList.add('on');repSection(b.dataset.r);});
  repSection('Fuel efficiency');
}

export async function repSection(which){
  const out=$('repOut');out.innerHTML='<div class="hint">Calculating…</div>';
  if(which==='Fuel efficiency'){
    const [{data:s},{data:rows}]=await Promise.all([
      db.from('report_fuel_summary').select('*').single(),
      db.from('report_fuel').select('*').order('cost_per_km',{ascending:false})]);
    out.innerHTML=`<div class="cards" style="margin-bottom:14px">
      ${statCard('Best mileage','Bus '+s.best_mileage_bus, s.best_mileage+' km/l')}
      ${statCard('Worst mileage','Bus '+s.worst_mileage_bus, s.worst_mileage+' km/l')}
      ${statCard('Avg cost / km', rupee(s.avg_cost_per_km))}
      ${statCard('Avg fuel / student', rupee(s.avg_fuel_per_student))}
      ${statCard('Total annual fuel', rupee(s.total_annual_fuel))}</div>
      <div class="note" style="margin-bottom:6px">Per bus, worst cost-per-km first — the buses to look at for re-routing or replacement.</div>`+
      repTable([{k:'bus_id',label:'Bus'},{k:'kmpl',label:'km/l'},{k:'students',label:'Students'},
        {k:'km_per_trip',label:'Km/trip'},{k:'cost_per_km',label:'Cost/km',fmt:rupee},
        {k:'fuel_per_student',label:'Fuel/student',fmt:rupee},{k:'annual_fuel',label:'Annual fuel',fmt:rupee}],rows||[],'fuel_efficiency');
  }
  else if(which==='Capacity'){
    const [{data:s},{data:rows}]=await Promise.all([
      db.from('report_capacity_summary').select('*').single(),
      db.from('report_capacity').select('*').order('utilisation_pct',{ascending:false})]);
    out.innerHTML=`<div class="cards" style="margin-bottom:14px">
      ${statCard('Average occupancy', s.avg_occupancy)}
      ${statCard('Peak occupancy', s.peak_occupancy,'Bus '+s.peak_bus)}
      ${statCard('Spare seats (fleet)', s.total_spare_seats)}
      ${statCard('Fleet utilisation', s.fleet_utilisation_pct+'%')}
      ${statCard('Over capacity', s.over_capacity_buses+' bus'+(s.over_capacity_buses==1?'':'es'))}
      ${statCard('Under 50% full', s.under_half_buses+' bus'+(s.under_half_buses==1?'':'es'))}</div>
      <div class="note" style="margin-bottom:6px">Utilisation = riders ÷ base capacity. Effective capacity includes the limit-break allowance.</div>`+
      repTable([{k:'bus_id',label:'Bus'},{k:'riders',label:'Riders'},{k:'capacity',label:'Capacity'},
        {k:'effective_capacity',label:'Effective'},{k:'spare',label:'Spare'},
        {k:'utilisation_pct',label:'Utilisation',fmt:v=>v+'%'}],rows||[],'capacity');
  }
  else if(which==='Finance'){
    const {data:f}=await db.from('report_finance').select('*').single();
    out.innerHTML=`<div class="cards" style="margin-bottom:14px">
      ${statCard('Annual revenue (fees)', rupee(f.annual_revenue))}
      ${statCard('Annual fuel expense', rupee(f.annual_fuel_expense))}
      ${statCard('Surplus over fuel', rupee(f.surplus_over_fuel))}
      ${statCard('Paying students', f.paying_students)}
      ${statCard('Average fee', rupee(f.avg_fee))}</div>
      <div class="note" style="max-width:680px">Surplus here is revenue minus <b>fuel only</b> — it does not include driver salaries, maintenance, insurance or depreciation, so it overstates true profit. <b>Outstanding transport fees</b> can't be shown yet because the database has each student's annual charge but no record of what's been paid. Add a <span class="mono">paid_amount</span> (or a payments table) and this becomes: outstanding = charged − paid. I can wire that in once fee-collection data exists.</div>`;
  }
  else if(which==='Start points'){
    const [{data:s},{data:rows}]=await Promise.all([
      db.from('report_deadrun_summary').select('*').single(),
      db.from('report_deadrun_full').select('*').order('dead_km',{ascending:false})]);
    out.innerHTML=`<div class="note" style="margin-bottom:10px">Every bus drives empty from its start point to its first student. That "dead run" burns fuel and time before a single child is aboard. Buses with a captured depot start there; the rest start from school. Distances are road-estimated.</div>
      <div class="cards" style="margin-bottom:14px">
        ${statCard('Start points too far', s.buses_far+' of '+s.buses_measured,'over 2 km')}
        ${statCard('Start from school', s.buses_from_school+' buses','no depot set')}
        ${statCard('Dead run / trip', s.total_dead_km_per_trip+' km')}
        ${statCard('Wasted fuel / yr', rupee(s.total_annual_dead_fuel))}
        ${statCard('Recoverable / yr', rupee(s.total_annual_savings_if_close),'if start ≤1.5 km')}</div>
      <div class="note" style="margin-bottom:6px">Per bus, worst dead-run first. "Start" shows whether the bus begins at its own depot or from school. "If close" = fuel saved per year if it started within 1.5 km of its first student.</div>`+
      repTable([{k:'bus_id',label:'Bus'},{k:'start_from',label:'Start'},{k:'first_student',label:'First student'},
        {k:'dead_km',label:'Dead run (km)'},{k:'dead_min_per_trip',label:'Dead min/trip'},
        {k:'annual_dead_fuel',label:'Wasted fuel/yr',fmt:rupee},
        {k:'savable_km',label:'Savable km',fmt:v=>Number(v).toFixed(2)},
        {k:'annual_savings_if_close',label:'Save/yr if ≤1.5km',fmt:rupee},
        {label:'',cell:r=>`<button class="b-ghost startmapbtn" data-bus="${r.bus_id}" style="font-size:12px;padding:3px 8px">Map</button>`}],rows||[],'start_points_deadrun');
  }
  else if(which==='Geography'){
    out.innerHTML=`<div class="note" style="margin-bottom:8px">Where students live, where routes run, and which routes overlap.</div>
      <div class="actions" style="margin-bottom:8px">
        <button class="b-ghost heatbtn on" data-m="students">Student density</button>
        <button class="b-ghost heatbtn" data-m="routes">Route density</button></div>
      <div id="repMap" style="height:440px;border:1px solid var(--edge);border-radius:8px"></div>
      <h3 style="margin:16px 0 6px;font-size:15px">Route overlap — shared corridors</h3>
      <div class="note" style="margin-bottom:6px">Pairs where one bus’s route runs within 300 m of another’s. High overlap = candidates to consolidate.</div>
      <div id="repOverlap"></div>`;
    setTimeout(()=>buildGeography(),50);
  }
  out.querySelectorAll('.repcsv').forEach(b=>b.onclick=()=>downloadRepCsv(b.closest('#repOut').querySelector(`table[data-title="${b.dataset.t}"]`),b.dataset.t));
  out.querySelectorAll('.startmapbtn').forEach(b=>b.onclick=()=>globalThis.showSuggestionOnMap('', [Number(b.dataset.bus)]));
}

export function downloadRepCsv(tbl,title){
  if(!tbl)return;const rows=[...tbl.querySelectorAll('tr')].map(tr=>[...tr.children].map(td=>`"${td.textContent.replace(/"/g,'""')}"`).join(','));
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download=title+'.csv';a.click();
}

export async function buildGeography(){
  if(!repMap){repMap=L.map('repMap').setView([school?school.latitude:27.578,school?school.longitude:75.137],11);
    addBaseLayer(repMap);}
  setTimeout(()=>repMap.invalidateSize(),60);
  const data=await fetchAll('bus_roster','latitude,longitude,pickup_order,bus_id');
  repStudentPts=(data||[]).filter(s=>s.latitude!=null).map(s=>[s.latitude,s.longitude,0.6]);
  // route density: sample midpoints between consecutive stops so corridors light up
  const byBus={};(data||[]).forEach(s=>{if(s.latitude!=null)(byBus[s.bus_id]=byBus[s.bus_id]||[]).push(s);});
  repRoutePts=[];
  Object.values(byBus).forEach(arr=>{arr.sort((a,b)=>(a.pickup_order||9999)-(b.pickup_order||9999));
    for(let i=0;i<arr.length-1;i++){const a=arr[i],b=arr[i+1];for(let t=0;t<=1;t+=0.25)repRoutePts.push([a.latitude+(b.latitude-a.latitude)*t,a.longitude+(b.longitude-a.longitude)*t,0.5]);}});
  drawHeat('students');
  [...document.querySelectorAll('.heatbtn')].forEach(b=>b.onclick=()=>{document.querySelectorAll('.heatbtn').forEach(x=>x.classList.remove('on'));b.classList.add('on');drawHeat(b.dataset.m);});
  const {data:ov}=await db.rpc('route_overlap',{p_metres:300});
  $('repOverlap').innerHTML=repTable([{k:'bus_a',label:'Bus A'},{k:'bus_b',label:'overlaps Bus B'},
    {k:'a_km',label:'A route km'},{k:'shared_km',label:'Shared km'},{k:'shared_pct',label:'Shared %',fmt:v=>v+'%'}],ov||[],'route_overlap');
  $('repOverlap').querySelectorAll('.repcsv').forEach(b=>b.onclick=()=>downloadRepCsv($('repOverlap').querySelector('table'),'route_overlap'));
}

export function drawHeat(mode){
  if(!L.heatLayer)return;
  if(repHeat){repMap.removeLayer(repHeat);repHeat=null;}
  const pts=mode==='routes'?repRoutePts:repStudentPts;
  repHeat=L.heatLayer(pts,{radius:mode==='routes'?12:18,blur:15,maxZoom:14}).addTo(repMap);
}

Object.assign(globalThis, { renderReports, repSection, downloadRepCsv, buildGeography, drawHeat });
