// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

export function orderStops(stops,depot,schoolPt){
  const withOrder=stops.filter(s=>s.pickup_order);
  if(withOrder.length>=stops.length*0.6)return stops.slice().sort((a,b)=>(a.pickup_order||9999)-(b.pickup_order||9999));
  if(stops.length<=2)return stops.slice();
  const P=stops.map(s=>[s.latitude,s.longitude]);let order=[],rem=stops.map((_,i)=>i),cur;
  if(depot)cur=depot;else if(schoolPt){let fi=0,fd=-1;rem.forEach(i=>{const d=hav(schoolPt[0],schoolPt[1],P[i][0],P[i][1]);if(d>fd){fd=d;fi=i;}});order.push(fi);rem=rem.filter(i=>i!==fi);cur=P[fi];}else cur=P[rem[0]];
  while(rem.length){let bi=rem[0],bd=1e9;rem.forEach(i=>{const d=hav(cur[0],cur[1],P[i][0],P[i][1]);if(d<bd){bd=d;bi=i;}});order.push(bi);rem=rem.filter(i=>i!==bi);cur=P[bi];}
  return order.map(i=>stops[i]);
}

Object.assign(globalThis, { orderStops });
