// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

import { roundBusIds, searchRoundStudents } from "./rounds.js";

export async function searchStudents(term){term=term.trim();
  if(term.length<2){$('results').innerHTML='<div class="hint">Type a name or SR number.</div>';return;}
  // follows the selected round, so Round 2 never lists Round-1 students
  const data=await searchRoundStudents(term,40);
  renderList($('results'),data,globalThis.tdRound===2?openStudentR2:openStudent);
}

/**
 * Round-2 children live in their own table and have no profile, temp-assignment or
 * fuel-share records, so they get their own compact editor rather than the Round-1 form.
 */
export async function openStudentR2(id){
  const {data,error}=await db.from('students_round2').select('*').eq('id',id).single();
  if(error){toast(error.message,'bad');return;}
  const ids=await roundBusIds();
  const busOpts=ids.map(b=>`<option value="${b}" ${String(b)===String(data.bus_no)?'selected':''}>Bus ${b}</option>`).join('');
  current=data;$('empty').style.display='none';const f=$('form');f.style.display='block';
  const pv=(k,v)=>`<div class="coord"><div class="k">${k}</div><div class="v">${v}</div></div>`;
  f.innerHTML=`<div style="display:flex;gap:10px;align-items:baseline;flex-wrap:wrap;margin-bottom:8px">
      <h2 style="margin:0;font-size:17px">${esc(data.name)}</h2><span class="note mono">SR ${esc(data.sr_no)}</span>
      <span class="note">Class ${esc(data.class||'')}${data.section?'-'+esc(data.section):''}</span>
      <span class="flag" style="background:var(--signal-soft);border-color:#f0d3a8">Round 2</span></div>
    <div class="grid" style="margin-bottom:8px">
      ${pv('Current bus','Bus '+esc(data.bus_no??'—'))}
      ${pv('Driving order',data.pickup_order??'—')}</div>
    <div class="note">Edit below — drag the pin or click the map to set the pickup point.</div>
    <div class="grid" style="margin-top:12px">
      <div class="coord"><div class="k">Latitude</div><div class="v mono" id="cLat">${data.latitude!=null?(+data.latitude).toFixed(6):'—'}</div></div>
      <div class="coord"><div class="k">Longitude</div><div class="v mono" id="cLon">${data.longitude!=null?(+data.longitude).toFixed(6):'—'}</div></div>
      <div><label>Round 2 bus</label><select id="busSelR2">${busOpts}</select></div>
      <div><label>Class</label><input id="clsR2" value="${esc(data.class||'')}"/></div>
      <div><label>Section</label><input id="secR2" value="${esc(data.section||'')}"/></div>
    </div>
    <div class="actions"><button class="b-primary" id="saveBtn" disabled>Save changes</button>
      <button class="b-ghost" id="resetBtn">Undo pin</button>
      <span class="note" id="lastEdit">${data.updated_by?('Last edited by '+esc(data.updated_by)):''}</span></div>
    <div class="note" style="margin-top:10px">Moving a child to another bus clears their driving order — re-run the Round 2 order from the Optimization tab afterwards so both routes stay correct.</div>`;
  if(data.latitude!=null){setPin(+data.latitude,+data.longitude,false);map.setView([+data.latitude,+data.longitude],16);}
  $('saveBtn').disabled=true;
  ['busSelR2','clsR2','secR2'].forEach(k=>$(k).oninput=$(k).onchange=()=>$('saveBtn').disabled=false);
  $('resetBtn').onclick=()=>{if(data.latitude!=null)setPin(+data.latitude,+data.longitude,false);$('saveBtn').disabled=true;};
  $('saveBtn').onclick=async()=>{
    const newBus=parseInt($('busSelR2').value,10);
    const rec={bus_no:newBus,class:$('clsR2').value.trim()||null,section:$('secR2').value.trim()||null,
      updated_at:new Date().toISOString()};
    const lat=parseFloat($('cLat').textContent),lon=parseFloat($('cLon').textContent);
    if(Number.isFinite(lat)&&Number.isFinite(lon)){rec.latitude=lat;rec.longitude=lon;}
    // a bus change makes the stored driving order meaningless for both buses
    if(String(newBus)!==String(data.bus_no)) rec.pickup_order=null;
    const {error}=await db.from('students_round2').update(rec).eq('id',id);
    if(error){toast(error.message,'bad');return;}
    toast('Saved','good');openStudentR2(id);
  };
}

export function renderList(box,data,onclick){
  if(!data||!data.length){box.innerHTML='<div class="hint">No match.</div>';return;}
  box.innerHTML=data.map(s=>`<div class="item" data-id="${s.id}"><span class="nm">${esc(s.student_name)}${(s.using_temp_address||s.using_temp_bus)?' <span class="flag">TEMP</span>':''}</span><span class="sr mono">${esc(s.sr_no)}</span><span class="bs">Bus ${esc(s.bus_id??'—')}</span></div>`).join('');
  [...box.querySelectorAll('.item')].forEach(el=>el.onclick=()=>{box.querySelectorAll('.item').forEach(x=>x.classList.remove('on'));el.classList.add('on');onclick(el.dataset.id);});
}

export async function openStudent(id){
  const {data,error}=await db.from('student_effective').select('*').eq('id',id).single();
  if(error){toast(error.message,'bad');return;}
  // road time to school for the profile
  const {data:rt}=await db.from('students').select('road_km_to_school,road_min_to_school,uses_transport').eq('id',id).single();
  const roadTxt = rt&&rt.road_min_to_school!=null ? `${rt.road_min_to_school} min (${rt.road_km_to_school} km)` : '—';
  const usesTransport = !rt || rt.uses_transport!==false;
  // full profile from the whole-school profile table
  const {data:prof}=await db.from('student_profiles').select('*').eq('sr_no',data.sr_no).maybeSingle();
  const parentName = data.parent_name || (prof&&prof.father_name) || null;
  const parentPhone = data.phone || (prof&&prof.father_phone) || null;
  current=data;$('empty').style.display='none';const f=$('form');f.style.display='block';
  const busOpts=buses.map(b=>`<option value="${b.bus_id}" ${String(b.bus_id)===String(data.permanent_bus)?'selected':''}>Bus ${b.bus_id} · ${b.capacity} seats</option>`).join('');
  const pv=(k,v)=>`<div class="coord"><div class="k">${k}</div><div class="v">${v}</div></div>`;
  f.innerHTML=`<div style="display:flex;gap:10px;align-items:baseline;flex-wrap:wrap;margin-bottom:8px">
      <h2 style="margin:0;font-size:17px">${esc(data.student_name)}</h2><span class="note mono">SR ${esc(data.sr_no)}</span>
      <span class="note">Class ${esc(data.class)}${data.section?'-'+esc(data.section):''}</span>
      ${data.using_temp_address?'<span class="flag">Temp address</span>':''}${data.using_temp_bus?'<span class="flag">Temp bus</span>':''}
      ${usesTransport?'':'<span class="flag" style="background:#eef;color:#446">Comes by self</span>'}</div>
    <div style="background:${usesTransport?'#f7f8fa':'#eef2ff'};border:1px solid var(--edge);border-radius:8px;padding:10px 12px;margin-bottom:10px;display:flex;align-items:center;gap:10px">
      <label style="display:flex;align-items:center;gap:8px;cursor:pointer;margin:0"><input type="checkbox" id="selfTransport" ${usesTransport?'':'checked'}> Comes by self (not on school transport)</label>
      <span class="note" style="margin-left:auto">${usesTransport?'Currently on Bus '+esc(data.bus_id):'Removed from bus rosters &amp; capacity'}</span>
    </div>
    <div class="grid" style="margin-bottom:8px">
      ${pv('Current bus','Bus '+esc(data.bus_id))}
      ${pv('Pickup order',data.pickup_order??'—')}
      ${pv('Time to school',roadTxt)}
      ${pv('Parent',esc(parentName||'—'))}
      ${pv('Phone',esc(parentPhone||'—'))}
      ${pv('Permanent bus','Bus '+esc(data.permanent_bus))}</div>
    ${prof?`<details open style="margin-bottom:10px"><summary style="cursor:pointer;font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--slate)">Student profile</summary>
      <div class="grid" style="margin-top:8px">
        ${pv('Father',esc(prof.father_name||'—'))}
        ${pv('Mother',esc(prof.mother_name||'—'))}
        ${pv('Father phone',esc(prof.father_phone||'—'))}
        ${pv('Mother phone',esc(prof.mother_phone||'—'))}
        ${pv('Date of birth',esc(prof.dob||'—'))}
        ${pv('Gender',esc(prof.gender||'—'))}
        ${pv('Admission date',esc(prof.admission_date||'—'))}
        ${pv('Previous school',esc(prof.previous_school||'—'))}</div>
      <div class="coord" style="margin-top:8px"><div class="k">Home address</div><div class="v">${esc(prof.home_address||'—')}</div></div>
      </details>`:`<div class="note" style="margin-bottom:10px">No profile on file for this student yet — upload the whole-school CSV in Bulk to add it.</div>`}
    <div class="note">Edit below — drag the pin or click the map to set the pickup point.</div>
    <div class="grid" style="margin-top:12px">
      <div class="coord"><div class="k">Latitude</div><div class="v mono" id="cLat">${(+data.permanent_latitude).toFixed(6)}</div></div>
      <div class="coord"><div class="k">Longitude</div><div class="v mono" id="cLon">${(+data.permanent_longitude).toFixed(6)}</div></div>
      <div><label>Permanent bus</label><select id="busSel">${busOpts}</select></div>
      <div><label>Pickup order</label><input id="pkIn" type="number" min="1" value="${data.pickup_order??''}" placeholder="unset"/></div>
      <div><label>Parent name</label><input id="parIn" value="${esc(data.parent_name||'')}"/></div>
      <div><label>Phone</label><input id="phIn" value="${esc(data.phone||'')}"/></div>
    </div>
    <div class="field" style="margin-top:12px"><label>Why the change (optional)</label><input id="noteIn" placeholder="e.g. shifted house"/></div>
    <div class="actions"><button class="b-primary" id="saveBtn" disabled>Save changes</button>
      <button class="b-ghost" id="resetBtn">Undo pin</button>
      <button class="b-ghost" id="leftBtn" style="color:#b42318;border-color:#e7b7b1;margin-left:auto">Student left school</button>
      <span class="note" id="lastEdit">${data.updated_by?('Last edited by '+esc(data.updated_by)):''}</span></div>
    <details><summary>Change history &amp; undo</summary><div id="hist" class="note" style="margin-top:8px">Loading…</div></details>`;
  setPin(+data.latitude,+data.longitude,false);map.setView([+data.latitude,+data.longitude],16);$('saveBtn').disabled=true;
  ['busSel','pkIn','parIn','phIn'].forEach(idf=>$(idf).oninput=$(idf).onchange=()=>$('saveBtn').disabled=false);
  $('selfTransport').onchange=()=>$('saveBtn').disabled=false;
  $('saveBtn').onclick=saveStudent;
  $('resetBtn').onclick=()=>{setPin(+data.latitude,+data.longitude,false);$('saveBtn').disabled=true;};
  $('leftBtn').onclick=removeStudent;
  loadHistory(data.id);
}

export async function removeStudent(){
  if(!current) return;
  if(!confirm(`Remove ${current.student_name} (SR ${current.sr_no}) from the school?\n\nThey will be taken off all buses, rosters and optimization. This is reversible (re-activate later if they return).`)) return;
  const {error}=await db.from('students').update({active:false}).eq('id',current.id);
  if(error){toast(error.message,'bad');return;}
  toast(current.student_name+' removed — left school','good');
  current=null;$('form').style.display='none';$('empty').style.display='block';
  if(pin){try{map.removeLayer(pin);}catch(e){}pin=undefined;}
  searchStudents($('q').value);loadDashboard();
}

export async function saveStudent(){
  const p=pin.getLatLng();const newBus=parseInt($('busSel').value,10);
  const comesBySelf=$('selfTransport').checked;
  const pk=$('pkIn').value?parseInt($('pkIn').value,10):null;const busChanged=newBus!==current.permanent_bus;
  const patch={latitude:+p.lat.toFixed(6),longitude:+p.lng.toFixed(6),bus_no:newBus,
    parent_name:$('parIn').value.trim()||null,phone:$('phIn').value.trim()||null,
    address_note:$('noteIn').value.trim()||null,
    uses_transport:!comesBySelf,
    pickup_order: comesBySelf ? null : (busChanged && $('pkIn').value===String(current.pickup_order??'') ? null : pk)};
  const {error}=await db.from('students').update(patch).eq('id',current.id);
  if(error){toast(error.message.includes('uniq_bus_pickup')?`Pickup position ${pk} is already used on bus ${newBus}`:error.message,'bad');return;}
  toast(comesBySelf?'Saved — student removed from school transport':('Saved'+(busChanged&&patch.pickup_order===null?' — set a pickup order on the Pickup tab':'')),'good');
  $('saveBtn').disabled=true;openStudent(current.id);searchStudents($('q').value);loadDashboard();
}

export async function loadHistory(id){
  const {data,error}=await db.from('student_address_history').select('id,changed_at,changed_by,old_latitude,new_latitude,old_longitude,new_longitude,old_bus_no,new_bus_no,old_pickup_order,new_pickup_order,note').eq('student_id',id).order('changed_at',{ascending:false}).limit(10);
  const box=$('hist');if(!box)return;
  if(error||!data||!data.length){box.textContent=error?error.message:'No changes recorded yet.';return;}
  box.innerHTML=data.map(h=>{const w=new Date(h.changed_at).toLocaleString();const bits=[];
    if(h.old_latitude!==h.new_latitude||h.old_longitude!==h.new_longitude)bits.push('address moved');
    if(h.old_bus_no!==h.new_bus_no)bits.push(`bus ${h.old_bus_no??'—'}→${h.new_bus_no??'—'}`);
    if(h.old_pickup_order!==h.new_pickup_order)bits.push(`pickup ${h.old_pickup_order??'—'}→${h.new_pickup_order??'—'}`);
    return `<div class="histrow"><span style="flex:1">${w} · ${esc(h.changed_by||'?')} — ${bits.join(', ')||'edited'}${h.note?' · '+esc(h.note):''}</span><button class="b-ghost" style="padding:3px 8px;font-size:11px" data-h="${h.id}">Undo</button></div>`;}).join('');
  [...box.querySelectorAll('button[data-h]')].forEach(b=>b.onclick=async()=>{
    const {error}=await db.rpc('revert_change',{p_history_id:parseInt(b.dataset.h,10)});
    if(error){toast(error.message,'bad');return;}toast('Change reverted','good');openStudent(id);});
}

Object.assign(globalThis, { searchStudents, renderList, openStudent, saveStudent, loadHistory, removeStudent });
