// Generated by tools/autorefactor.py. Do not edit while migration is repeatable.
// Functions access legacy runtime state through the global bridge in app.js.

export async function fetchAll(table,columns){
  const N=1000;let from=0,all=[];
  while(true){
    const {data,error}=await db.from(table).select(columns).range(from,from+N-1);
    if(error){console.error(error);break;}
    all=all.concat(data||[]);
    if(!data||data.length<N)break;
    from+=N;
  }
  return all;
}

export function toast(m,k){const t=$('toast');t.textContent=m;t.className='show '+(k||'');setTimeout(()=>t.className='',3400);}

export function hav(a,b,c,d){const R=6371,r=Math.PI/180,x=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return 2*R*Math.asin(Math.sqrt(x));}

export function norm(s){return (s||'').toString().trim().toLowerCase().replace(/[^a-z0-9]/g,'');}

export function pick(row, keys){ // find a value by any of several loose header names
  const map={}; for(const k in row) map[norm(k)]=row[k];
  for(const want of keys){ const v=map[norm(want)]; if(v!==undefined && String(v).trim()!=='') return String(v).trim(); }
  return null;
}

export function isoDate(s){ if(!s)return null; const m=String(s).trim().match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/); if(!m)return null;
  const[_,d,mo,y]=m; const dt=`${y}-${mo.padStart(2,'0')}-${d.padStart(2,'0')}`; return dt; }

export function digits(s){ if(!s)return null; const d=String(s).replace(/\D/g,''); return d||null; }

export function repTable(cols,rows,title){
  const head=cols.map(c=>`<th>${esc(c.label)}</th>`).join('');
  const body=rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(c.fmt?c.fmt(r[c.k]):(r[c.k]??''))}</td>`).join('')+'</tr>').join('');
  return `<div class="actions" style="margin:6px 0"><button class="b-ghost repcsv" data-t="${esc(title)}">Download CSV</button><span class="note">${rows.length} rows</span></div>
    <div style="background:#fff;border:1px solid var(--edge);border-radius:8px;overflow:auto"><table data-title="${esc(title)}"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
}

export function statCard(label,val,sub){return `<div class="stat"><b>${val}</b><span>${label}${sub?` · ${sub}`:''}</span></div>`;}

export function table(cols,rows,empty){if(!rows||!rows.length)return `<div class="note">${empty||'No rows.'}</div>`;
  return `<div style="background:#fff;border:1px solid var(--edge);border-radius:8px;overflow:auto;margin-top:8px"><table><thead><tr>${cols.map(c=>`<th>${esc(c.replace(/_/g,' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c]??'')}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`;}

// Legacy helper exports retained for bootstrap compatibility.
export const $ = (...args) => globalThis.$(...args);
export const esc = (...args) => globalThis.esc(...args);
export const rs = (...args) => globalThis.rs(...args);
export const rupee = (...args) => globalThis.rupee(...args);

Object.assign(globalThis, { fetchAll, toast, hav, norm, pick, isoDate, digits, repTable, statCard, table });
