"""One-command, reversible frontend migration for TransportDesk.

Usage:
    python tools/autorefactor.py             # migrate and verify
    python tools/autorefactor.py --dry-run   # report only, write nothing
    python tools/autorefactor.py --restore BACKUP_DIRECTORY
"""
from __future__ import annotations
import argparse, json, shutil, sys
from datetime import datetime, timezone
from pathlib import Path

from refactor_core import (MODULES, blank_ranges, classify, extract_functions,
                           globalize_declarations, module_text, remove_imports,
                           top_level_imports, top_level_declarations)
from refactor_verify import verify


def backup(root: Path, js_dir: Path) -> Path:
    destination = root / "backups" / f"autorefactor-{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}"
    destination.mkdir(parents=True, exist_ok=False)
    shutil.copytree(js_dir, destination / "js")
    return destination


def restore(root: Path, source: Path) -> None:
    target = root / "frontend" / "js"
    saved = source / "js"
    if not saved.is_dir(): raise SystemExit(f"Not an autorefactor backup: {source}")
    for old in target.glob("*.js"): old.unlink()
    shutil.copytree(saved, target, dirs_exist_ok=True)


def plan(root: Path) -> tuple[dict, str, dict[str, str]]:
    js_dir = root / "frontend" / "js"; source = js_dir / "app.js"
    if not source.exists(): raise SystemExit(f"Cannot find {source}")
    original = source.read_text(encoding="utf-8")
    functions = extract_functions(original)
    if not functions: raise SystemExit("No top-level named functions found; no files changed.")
    groups = {module: [] for module in MODULES}
    for fn in functions: groups[classify(fn)].append(fn)
    runtime = blank_ranges(original, [(fn.start, fn.end) for fn in functions])
    bridge_names = sorted(top_level_declarations(original))
    imports = top_level_imports(runtime)
    runtime = globalize_declarations(remove_imports(runtime))
    side_effects = "\n".join(f'import "./{module}.js";' for module in MODULES)
    # Existing named imports (start/navigate/createClient) remain; deduping is source based.
    app = ("// Generated by tools/autorefactor.py. Original saved in backups/.\n"
           + "\n".join(imports) + "\n" + side_effects + "\n\n" + runtime.strip() + "\n")
    # Function bodies in generated modules keep the legacy unqualified names.
    # Publish every original top-level declaration after initialization so those
    # names resolve through the global environment when a handler later runs.
    if bridge_names:
        app += "\nObject.assign(globalThis, { " + ", ".join(bridge_names) + " });\n"
    files = {f"{module}.js": module_text(module, funcs) for module, funcs in groups.items() if funcs}
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(), "source": str(source),
        "function_count": len(functions), "functions": [fn.name for fn in functions],
        "modules": {module: [fn.name for fn in funcs] for module, funcs in groups.items()},
        "notes": ["Modules use a temporary global bridge to preserve the legacy app's shared mutable state.",
                  "After verification, globals can be migrated to explicit state imports incrementally."],
    }
    return report, app, files


def main() -> int:
    parser = argparse.ArgumentParser(description="Safely split frontend/js/app.js into ES modules.")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--dry-run", action="store_true", help="show the plan without changing files")
    parser.add_argument("--restore", type=Path, metavar="BACKUP", help="restore a backup directory")
    args = parser.parse_args(); root = args.root.resolve()
    if args.restore:
        restore(root, args.restore.resolve()); print(f"Restored {args.restore}"); return 0
    source = root / "frontend" / "js" / "app.js"
    if source.exists() and "Generated by tools/autorefactor.py" in source.read_text(encoding="utf-8"):
        report_path = root / "backups" / "autorefactor-last-report.json"
        report = json.loads(report_path.read_text(encoding="utf-8")) if report_path.exists() else {}
        problems = verify(root / "frontend" / "js", report)
        if report_path.exists():
            report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print("Already migrated; verification passed." if not problems else "Already migrated; verification failed.")
        return 0 if not problems else 1
    report, app, files = plan(root)
    print(f"Found {report['function_count']} functions.")
    for name, members in report["modules"].items(): print(f"  {name:10} {len(members):2}  {', '.join(members)}")
    if args.dry_run: print("Dry run: no files changed."); return 0
    js_dir = root / "frontend" / "js"; saved = backup(root, js_dir)
    try:
        # A module with no matching source function may have been manually split
        # already (the dashboard is one such case). Preserve it rather than
        # replacing working code with an empty generated file.
        for module in MODULES:
            generated = files.get(f"{module}.js")
            if generated is not None:
                (js_dir / f"{module}.js").write_text(generated, encoding="utf-8")
        (js_dir / "app.js").write_text(app, encoding="utf-8")
        problems = verify(js_dir, report)
        (root / "backups" / "autorefactor-last-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
        if problems:
            print("Migration written but verification found problems. Restore with:")
            print(f"  python tools/autorefactor.py --restore \"{saved}\"")
            return 1
    except Exception:
        restore(root, saved); raise
    print(f"Migration complete. Backup: {saved}")
    print(f"Report: {root / 'backups' / 'autorefactor-last-report.json'}")
    return 0

if __name__ == "__main__": raise SystemExit(main())
