"""Static safety checks for the generated TransportDesk frontend split."""
from __future__ import annotations
import json
from pathlib import Path
from refactor_core import extract_functions, identifiers, MODULES

BUILTINS = {
    "Array", "Boolean", "Date", "Error", "JSON", "Math", "Number", "Object",
    "Promise", "Set", "String", "URL", "console", "document", "window",
    "globalThis", "location", "fetch", "setTimeout", "clearTimeout", "parseInt",
    "encodeURIComponent", "decodeURIComponent", "Blob", "FileReader", "L",
}


def verify(js_dir: Path, report: dict) -> list[str]:
    problems: list[str] = []
    exports: set[str] = set()
    for module in MODULES:
        path = js_dir / f"{module}.js"
        if not path.exists(): problems.append(f"missing generated module: {path.name}"); continue
        text = path.read_text(encoding="utf-8")
        generated = "Generated by tools/autorefactor.py" in text
        for fn in extract_functions(text):
            # Pre-existing modules may intentionally keep private helpers. Only
            # generated modules promise to export every moved top-level function.
            if generated and not fn.text.lstrip().startswith("export "):
                problems.append(f"{module}.js: {fn.name} is not exported")
            exports.add(fn.name)
    app = js_dir / "app.js"
    app_text = app.read_text(encoding="utf-8")
    for module in MODULES:
        if f'./{module}.js' not in app_text:
            problems.append(f"app.js does not load {module}.js")
    expected = set(report.get("functions", []))
    lost = expected - exports
    if lost: problems.append("functions missing from generated modules: " + ", ".join(sorted(lost)))
    report["verification"] = {"passed": not problems, "problems": problems,
                              "exported_functions": sorted(exports)}
    return problems


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="Verify an autorefactor migration")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    report_path = args.root / "backups" / "autorefactor-last-report.json"
    report = json.loads(report_path.read_text(encoding="utf-8")) if report_path.exists() else {}
    problems = verify(args.root / "frontend" / "js", report)
    if report_path.exists():
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("Verification passed." if not problems else "Verification failed:\n- " + "\n- ".join(problems))
    return 0 if not problems else 1

if __name__ == "__main__": raise SystemExit(main())
